MADNESS: oep.cc File Reference
oep.cc File Reference
#include <madness/chem/oep.h>
#include <madness/misc/info.h>
Functions
int main (int argc, char **argv)
void write_test_input ()
Create a specific test input for the Be atom.
Function Documentation
main()
int main (int argc, char ** argv)
References madness::finalize(), madness::OEP::help(), madness::initialize(), madness::commandlineparser::key_exists(), molecule, madness::nonlinear_vector_solver(), madness::print(), madness::print_header1(), madness::OEP::print_parameters(), madness::info::print_revision_information(), madness::World::rank(), madness::commandlineparser::set_keyval(), madness::startup(), and test().
write_test_input()
void write_test_input ()
Create a specific test input for the Be atom.
References madness::filename, and madness::nonlinear_vector_solver().