MADNESS: bind_defaults.cpp File Reference
bind_defaults.cpp File Reference
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <madness/mra/mra.h>
Functions
void bind_defaults (py::module_ &m)
template<std::size_t NDIM>
static void bind_function_defaults (py::module_ &m, const char *name)
Function Documentation
bind_defaults()
void bind_defaults (py::module_ & m)
References m, and madness::nonlinear_vector_solver().
Referenced by PYBIND11_MODULE().
bind_function_defaults()
template<std::size_t NDIM> static void bind_function_defaults (py::module_ & m, const char * name) static
References m, madness::name(), and madness::nonlinear_vector_solver().