MADNESS: colloid.cc File Reference
colloid.cc File Reference
#include "molecularmask.h"
#include <madness/mra/nonlinsol.h>
#include <madness/mra/mra.h>
#include <madness/mra/lbdeux.h>
#include <madness/misc/ran.h>
#include <madness/tensor/solvers.h>
#include <ctime>
#include <list>
#include <jacob/molecule.h>
#include <madness/mra/sdf_shape_3D.h>
#include <madness/mra/funcplot.h>
#include <madness/constants.h>
#include <cmath>
#include <vector>
Classes
struct SurfaceMoleculeInteraction::Bop
struct SurfaceMoleculeInteraction::Reciprocal< T, NDIM >
class SurfaceMoleculeInteraction
Typedefs
typedef real_function_3d realfunc
Functions
double charge_function (const coord_3d &r)
double distance1 (const coord_3d &r, const coord_3d &center)
double electronic_charge_function (const coord_3d &r)
int main (int argc, char **argv)
double nuclear_charge_function (const coord_3d &r)
Typedef Documentation
realfunc
typedef real_function_3d realfunc
Function Documentation
charge_function()
double charge_function (const coord_3d & r)
References electronic_charge_function(), and nuclear_charge_function().
Referenced by main().
distance1()
double distance1 (const coord_3d & r, const coord_3d & center) inline
References madness::nonlinear_vector_solver().
electronic_charge_function()
double electronic_charge_function (const coord_3d & r)
References madness::nonlinear_vector_solver(), and madness::constants::pi.
Referenced by charge_function().
main()
int main (int argc, char ** argv)
References charge_function(), SafeMPI::COMM_WORLD, d, e(), madness::finalize(), madness::initialize(), k, L, lo, maxiter, madness::nonlinear_vector_solver(), madness::plot_line(), madness::print(), R, madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), sigma, madness::startup(), thresh, and madness::Function< T, NDIM >::trace().
nuclear_charge_function()
double nuclear_charge_function (const coord_3d & r)
References madness::nonlinear_vector_solver(), madness::constants::pi, and pow().
Referenced by charge_function().