MADNESS: dielectric.cc File Reference
dielectric.cc File Reference
Example solution of Poisson's equation in a dielectric (polarizable) medium.
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/mra/funcplot.h>
#include <madness/tensor/solvers.h>
#include "molecularmask.h"
#include <madness/mra/nonlinsol.h>
#include <madness/constants.h>
#include <vector>
Macros
#define TIME(MSG, X)
Functions
double charge_function (const coord_3d &r)
double exact_function (const coord_3d &x)
int main (int argc, char **argv)
double reciprocal (double x)
Variables
const double epsilon_0 = 1.0
const double epsilon_1 =10.0
const int k = 6
const double L = 5
const double R = 2.0
const double sigma = 0.1
const double thresh = 1e-4
double XXstart
Detailed Description
Example solution of Poisson's equation in a dielectric (polarizable) medium.
Macro Definition Documentation
TIME
#define TIME (MSG, X)
Value:
                    XXstart=wall_time();         \
                    X; \
                    if (world.rank() == 0) print("timer:",MSG,"used",wall_time()-XXstart) \
Function Documentation
charge_function()
double charge_function (const coord_3d & r)
References madness::nonlinear_vector_solver(), madness::constants::pi, and pow().
Referenced by main().
exact_function()
double exact_function (const coord_3d & x)
References epsilon_0, epsilon_1, madness::nonlinear_vector_solver(), and R.
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::_(), madness::BC_FREE, charge_function(), SafeMPI::COMM_WORLD, madness::CoulombOperator(), epsilon_0, epsilon_1, exact, exact_function(), madness::f, madness::finalize(), madness::initialize(), k, L, lo, madness::nonlinear_vector_solver(), madness::norm2(), op(), madness::constants::pi, madness::plot_line(), madness::plotdx(), madness::print(), R, reciprocal(), madness::FunctionDefaults< NDIM >::set_bc(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), sigma, madness::startup(), thresh, TIME, madness::truncate(), u(), madness::Function< T, NDIM >::unaryop(), and madness::NonlinearSolverND< NDIM >::update().
reciprocal()
double reciprocal (double x)
Referenced by main().
Variable Documentation
epsilon_0
const double epsilon_0 = 1.0
Referenced by exact_function(), and main().
epsilon_1
const double epsilon_1 =10.0
Referenced by exact_function(), and main().
k
const int k = 6
Referenced by main().
L
const double L = 5
Referenced by main().
R
const double R = 2.0
Referenced by exact_function(), and main().
sigma
const double sigma = 0.1
Referenced by madness::MP3::compute_mp3_ef_low_scaling(), DF::diagonalize(), madness::SCF::initial_guess_from_nwchem(), main(), madness::smooth< T, NDIM >::make_sigma(), madness::smooth< T, NDIM >::smooth_sigma(), test_gconv(), and madness::Localizer::undo_rotation().
thresh
const double thresh = 1e-4
Referenced by main().
XXstart
double XXstart