MADNESS: fcwf.h File Reference
fcwf.h File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <vector>
#include <math.h>
#include <complex>
Classes
class Fcwf
class Fcwf_vector_allocator
Functions
Fcwf apply (World &world, complex_derivative_3d &op, const Fcwf &psi)
Fcwf apply (World &world, real_convolution_3d &op, const Fcwf &psi)
Fcwf copy (Fcwf psi)
std::complex< double > inner (const Fcwf &psi, const Fcwf &phi)
std::complex< double > inner (std::vector< Fcwf > &a, std::vector< Fcwf > &b)
complex_function_3d inner_func (World &world, Fcwf &psi, Fcwf &phi)
Tensor< std::complex< double > > matrix_inner (World &world, std::vector< Fcwf > &a, std::vector< Fcwf > &b)
std::vector< Fcwf > operator* (const std::vector< Fcwf > &psis, std::complex< double > a)
std::vector< Fcwf > operator* (std::complex< double > a, const std::vector< Fcwf > &psis)
void operator+= (std::vector< Fcwf > &phi, const std::vector< Fcwf > &psi)
std::vector< Fcwf > operator- (const std::vector< Fcwf > &phi, const std::vector< Fcwf > &psi)
real_function_3d squaremod (Fcwf &psi)
real_function_3d squaremod_large (Fcwf &psi)
real_function_3d squaremod_small (Fcwf &psi)
std::vector< Fcwf > transform (World &world, std::vector< Fcwf > &a, Tensor< std::complex< double > > U)
Function Documentation
apply() [1/2]
Fcwf apply (World & world, complex_derivative_3d & op, const Fcwf & psi)
References copy(), madness::nonlinear_vector_solver(), and psi().
apply() [2/2]
Fcwf apply (World & world, real_convolution_3d & op, const Fcwf & psi)
References copy(), madness::nonlinear_vector_solver(), op(), and psi().
Referenced by madness::SCF::compute_residual(), kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), main(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeRow::row(), and madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeRow::row_fetch_compute().
copy()
Fcwf copy (Fcwf psi)
References psi().
Referenced by Fcwf::Fcwf(), apply(), apply(), dft_xc_lda_ene(), dft_xc_lda_V(), inner_func(), main(), Fcwf::operator+(), Fcwf::operator+=(), Fcwf::operator-(), Fcwf::operator-=(), F::operator=(), slymer::NWChem_Interface::read_movecs(), madness::Exchange< T, NDIM >::ExchangeImpl< T, NDIM >::MacroTaskExchangeRow::row_fetch_compute(), AtomicBasis::set_guess_info(), and vector_to_PQ().
inner() [1/2]
std::complex< double > inner (const Fcwf & psi, const Fcwf & phi)
References Fcwf::getinitialize(), MADNESS_ASSERT, and psi().
Referenced by madness::PotentialManager::core_projection(), madness::PotentialManager::core_projector_derivative(), inner(), and kinetic_energy_matrix_slow().
inner() [2/2]
std::complex< double > inner (std::vector< Fcwf > & a, std::vector< Fcwf > & b)
References a, b, inner(), and MADNESS_ASSERT.
inner_func()
complex_function_3d inner_func (World & world, Fcwf & psi, Fcwf & phi)
References a, b, c, madness::conj(), copy(), Fcwf::getinitialize(), MADNESS_ASSERT, madness::mul(), psi(), Fcwf::scale(), and sum.
matrix_inner()
Tensor< std::complex< double > > matrix_inner (World & world, std::vector< Fcwf > & a, std::vector< Fcwf > & b)
References a, b, m, matrix_inner(), madness::nonlinear_vector_solver(), and madness::BaseTensor::size().
Referenced by kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), and matrix_inner().
operator*() [1/2]
std::vector< Fcwf > operator* (const std::vector< Fcwf > & psis, std::complex< double > a)
References a, and madness::nonlinear_vector_solver().
operator*() [2/2]
std::vector< Fcwf > operator* (std::complex< double > a, const std::vector< Fcwf > & psis)
References a, and madness::nonlinear_vector_solver().
operator+=()
void operator+= (std::vector< Fcwf > & phi, const std::vector< Fcwf > & psi)
References MADNESS_ASSERT, and psi().
operator-()
std::vector< Fcwf > operator- (const std::vector< Fcwf > & phi, const std::vector< Fcwf > & psi)
References MADNESS_ASSERT, and psi().
squaremod()
real_function_3d squaremod (Fcwf & psi)
References madness::abssq(), MADNESS_ASSERT, madness::nonlinear_vector_solver(), psi(), and madness::Function< T, NDIM >::scale().
Referenced by DF::diagonalize(), DF::iterate(), DF::make_density_lineplots(), and DF::solve_occupied().
squaremod_large()
real_function_3d squaremod_large (Fcwf & psi)
References madness::abssq(), MADNESS_ASSERT, madness::nonlinear_vector_solver(), and psi().
Referenced by DF::make_component_lineplots(), and DF::make_component_logplots().
squaremod_small()
real_function_3d squaremod_small (Fcwf & psi)
References madness::abssq(), MADNESS_ASSERT, madness::nonlinear_vector_solver(), psi(), and madness::scale().
Referenced by DF::make_component_lineplots(), and DF::make_component_logplots().
transform()
std::vector< Fcwf > transform (World & world, std::vector< Fcwf > & a, Tensor< std::complex< double > > U)
References a, k, m, MADNESS_ASSERT, madness::nonlinear_vector_solver(), madness::BaseTensor::size(), and transform().
Referenced by main(), transform(), and transform3d().