MADNESS: functionio.cc File Reference
functionio.cc File Reference
Example of I/O with functions.
#include <madness/mra/mra.h>
#include <madness/constants.h>
Functions
static double function (const coord_3d &r)
Normalized gaussian.
int main (int argc, char **argv)
Variables
static const double L = 10
Detailed Description
Example of I/O with functions.
Function Documentation
function()
static double function (const coord_3d & r) static
Normalized gaussian.
References alpha, madness::nonlinear_vector_solver(), madness::constants::pi, and pow().
Referenced by madness::MP2::add_local_coupling(), madness::F12Potentials::convolve_with_fg(), madness::F12Potentials::convolve_with_local_U(), main(), madness::MP3::mp3_energy_contribution_macrotask_driver(), madness::munging_operator::operator()(), madness::MacroTaskComputeCorrelationEnergy::operator()(), madness::plot_along(), madness::plot_plane(), madness::plotdx(), madness::plotpovray(), plotvtk(), madness::plotvtk_data(), madness::plotvtk_data(), SafeMPI::detail::print_mpi_error(), madness::WorldProfile::register_id(), madness::CC2::solve(), and madness::MP2::solve_coupled_equations().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::f, madness::filename, madness::finalize(), function(), madness::g, h(), madness::initialize(), L, madness::nonlinear_vector_solver(), madness::norm2(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), and madness::startup().
Variable Documentation
L
const double L = 10 static
Referenced by main().