MADNESS: gfit.cc File Reference
gfit.cc File Reference
#include <madness/tensor/tensor_lapack.h>
#include <madness/tensor/solvers.h>
#include <madness/world/print.h>
#include <cmath>
#include <iostream>
#include <algorithm>
Classes
class Fred
Wrapper around vector demonstrating interface necessary.
Functions
double Akernel (double p)
Tensor< double > arithmetic_series (long n, double a, double h)
double E0 (double p)
double errsq (const Tensor< double > f, const Tensor< double > x, const Tensor< double > w, const Tensor< double > c, const Tensor< double > expnt, const double mu, const double p)
double fit (double x, const Tensor< double > &c, const Tensor< double > &expnt)
Tensor< double > geometric_series (long n, double a, double r)
int main ()
Tensor< double > map_tensor (double(*f)(double), const Tensor< double > &x)
double myexp (double x)
Tensor< double > optimize_coeffs (const Tensor< double > &f, const Tensor< double > &x, const Tensor< double > &w, const Tensor< double > &expnt, const double mu, const double p, const bool prnt=0)
double reciprocal (double x)
double square (double x)
Variables
const double c = 137.0359895
const double m = 1
const double mc2 = m*c*c
Function Documentation
Akernel()
double Akernel (double p)
References E0(), mc2, madness::nonlinear_vector_solver(), and p().
Referenced by main().
arithmetic_series()
Tensor< double > arithmetic_series (long n, double a, double h)
References a, h(), and q().
E0()
double E0 (double p)
References c, mc2, madness::nonlinear_vector_solver(), and p().
Referenced by Akernel().
errsq()
double errsq (const Tensor< double > f, const Tensor< double > x, const Tensor< double > w, const Tensor< double > c, const Tensor< double > expnt, const double mu, const double p)
References c, madness::f, fit(), mu, p(), pow(), madness::BaseTensor::size(), sum, and w().
Referenced by Fred::gradient(), main(), test_math(), Fred::value(), and Fred::value_and_gradient().
fit()
double fit (double x, const Tensor< double > & c, const Tensor< double > & expnt)
References c, myexp(), madness::BaseTensor::size(), and sum.
Referenced by errsq(), and main().
geometric_series()
Tensor< double > geometric_series (long n, double a, double r)
References a, and q().
Referenced by main().
main()
int main (void)
References madness::abs(), Akernel(), c, e(), errsq(), madness::f, fit(), geometric_series(), h(), map_tensor(), max, mu, madness::nonlinear_vector_solver(), opt(), optimize_coeffs(), p(), pow(), madness::print(), madness::Tensor< T >::ptr(), reciprocal(), madness::BaseTensor::size(), and w().
map_tensor()
Tensor< double > map_tensor (double(*)(double) f, const Tensor< double > & x)
References madness::copy(), madness::f, and madness::Tensor< T >::unaryop().
Referenced by main().
myexp()
double myexp (double x)
References madness::nonlinear_vector_solver().
Referenced by fit(), Fred::make_g(), and optimize_coeffs().
optimize_coeffs()
Tensor< double > optimize_coeffs (const Tensor< double > & f, const Tensor< double > & x, const Tensor< double > & w, const Tensor< double > & expnt, const double mu, const double p, const bool prnt = 0)
References b, c, e(), madness::f, madness::gelss(), mu, myexp(), madness::nonlinear_vector_solver(), p(), pow(), madness::BaseTensor::size(), and w().
Referenced by main(), and Fred::value_and_gradient().
reciprocal()
double reciprocal (double x)
Referenced by main().
square()
double square (double x)
Variable Documentation
c
const double c = 137.0359895
Referenced by E0(), errsq(), fit(), main(), and optimize_coeffs().
m
const double m = 1
mc2
const double mc2 = m*c*c
Referenced by Akernel(), and E0().