MADNESS: hatom_energy.cc File Reference
hatom_energy.cc File Reference
Compute the energy of the hydrogen atom ground state.
#include <madness/mra/mra.h>
Functions
int main (int argc, char **argv)
double psi (const Vector< double, 3 > &r)
double V (const Vector< double, 3 > &r)
Detailed Description
Compute the energy of the hydrogen atom ground state.
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::finalize(), SafeMPI::Intracomm::Get_rank(), madness::initialize(), madness::World::mpi, madness::nonlinear_vector_solver(), madness::print(), psi(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::startup(), u(), V(), and v.
psi()
double psi (const Vector< double, 3 > & r)
References e(), and madness::nonlinear_vector_solver().
Referenced by madness::BSHApply< T, NDIM >::add_coupling_and_levelshift(), APPLY(), APPLY(), APPLY(), apply(), apply(), apply_laplacian(), apply_potential(), apply_potential(), madness::GTHPseudopotential< Q >::apply_potential(), apply_potential(), MiniDFT::apply_potential(), madness::GTHPseudopotential< Q >::apply_potential_simple(), apply_T(), apply_U_ecf(), apply_U_mix(), apply_U_ncf(), apply_V(), madness::Solver< T, NDIM >::build_fock_matrix(), madness::HartreeFock< T, NDIM >::calculate_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_exchange_energy(), madness::HartreeFock< T, NDIM >::calculate_ke_sp(), madness::DFT< T, NDIM >::calculate_ke_sp(), madness::HartreeFock< T, NDIM >::calculate_pe_sp(), madness::HartreeFock< T, NDIM >::calculate_tot_coulomb_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_exchange_energy(), madness::HartreeFock< T, NDIM >::calculate_tot_ke_sp(), madness::DFT< T, NDIM >::calculate_tot_ke_sp(), madness::HartreeFock< T, NDIM >::calculate_tot_pe_sp(), compute_energy(), compute_energy(), compute_energy(), compute_energy(), compute_energy(), compute_energy_simple(), compute_energy_with_U(), madness::Localizer::compute_localization_matrix(), compute_R2f2_psi(), madness::SCF::compute_residual(), madness::Znemo::compute_residuals(), converge(), converge(), converge2s(), copy(), madness::PotentialManager::core_projection(), madness::SCF::diag_fock_matrix(), MiniDFT::doit(), doit(), doplotptk(), energy(), energy(), energy(), energy(), madness::Nemo::get_coulomb_potential(), initial_guess(), initial_loadbal(), inner(), inner_func(), iterate(), iterate(), iterate(), iterate(), iterate(), iterate(), iterate(), iterate(), iterate_excite(), iterate_excite(), iterate_ground(), iterate_ground(), iterate_xy(), iterate_xy(), line_plot(), load_balance(), loadbal(), loadbal(), loadbal(), logplot(), main(), madness::SCF::make_fock_matrix(), multiply_by_V(), madness::HartreeFockExchangeOp< T, NDIM >::op_o(), madness::DFTNuclearPotentialOp< T, NDIM >::op_r(), madness::DFTCoulombOp< T, NDIM >::op_r(), madness::DFTCoulombPeriodicOp< T, NDIM >::op_r(), madness::XCFunctionalLDA< T, NDIM >::op_r(), madness::DFTNuclearChargeDensityOp< T, NDIM >::op_r(), NuclearChargeDensityOp< T, NDIM >::op_r(), madness::HartreeFockNuclearPotentialOp< T, NDIM >::op_r(), madness::HartreeFockCoulombOp< T, NDIM >::op_r(), PsiExact::operator()(), Guess::operator()(), madness::BSHApply< T, NDIM >::operator()(), operator+=(), operator-(), MiniDFT::orthogonalize(), orthogonalize(), preloadbal(), print_info(), print_info(), print_stats(), print_stats(), propagate(), propagate(), propagate(), psi_exact(), reconstruct_psi(), DF::rele(), run(), madness::EigSolver< T, NDIM >::solve(), squaremod(), squaremod_large(), squaremod_small(), sympgrad4(), sympgrad6(), test2(), test_chin_chen(), test_he(), test_he_potential(), test_hf_h2(), test_hf_he(), test_hydro(), test_modified(), test_qm(), test_trotter(), test_U_el(), trotter(), madness::SCF::twoint(), update(), MiniDFT::update(), update(), wave_function_load(), and wave_function_store().
V()
double V (const Vector< double, 3 > & r)
References e(), and madness::nonlinear_vector_solver().
Referenced by main().