MADNESS: jimkernel.cc File Reference
jimkernel.cc File Reference
#include <madness/tensor/tensor.h>
#include <madness/world/print.h>
#include <madness/world/timers.h>
#include <vector>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References madness::aligned_add(), madness::aligned_sub(), c, madness::cpu_time(), k, m, madness::mTxmq(), madness::nonlinear_vector_solver(), madness::print(), madness::Tensor< T >::ptr(), smalltest, and Z.