MADNESS: mentity.cc File Reference
mentity.cc File Reference
Simple management of molecular information and potential.
#include <madness/mra/mra.h>
#include <madness/constants.h>
#include "mentity.h"
#include <madness/misc/misc.h>
Functions
static double distance (double x1, double y1, double z1, double x2, double y2, double z2)
static double distance_sq (double x1, double y1, double z1, double x2, double y2, double z2)
static double dsmoothed_potential (double r)
Derivative of the regularized 1/r potential.
const AtomicData & get_atomic_data (unsigned int atomic_number)
std::ostream & operator<< (std::ostream &s, const Atom &atom)
static double smoothed_density (double r)
Charge density corresponding to smoothed 1/r potential.
static double smoothed_potential (double r)
Regularized 1/r potential.
static double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
unsigned int symbol_to_atomic_number (const std::string &symbol)
Variables
static const AtomicData atomic_data [NUMBER_OF_ATOMS_IN_TABLE]
static const unsigned int NUMBER_OF_ATOMS_IN_TABLE = 110
static const double PI = 3.1415926535897932384
Detailed Description
Simple management of molecular information and potential.
Function Documentation
distance()
static double distance (double x1, double y1, double z1, double x2, double y2, double z2) inline static
References madness::nonlinear_vector_solver().
Referenced by MolecularEntity::inter_atomic_distance(), and MolecularEntity::nuclear_attraction_potential().
distance_sq()
static double distance_sq (double x1, double y1, double z1, double x2, double y2, double z2) inline static
References madness::nonlinear_vector_solver().
dsmoothed_potential()
static double dsmoothed_potential (double r) static
Derivative of the regularized 1/r potential.
dV/dx = (x/r) * du(r/c)/(c*c)
References e(), madness::nonlinear_vector_solver(), and madness::r2().
Referenced by madness::PseudoNuclearCorrelationFactor::U2X_spherical().
get_atomic_data()
const AtomicData & get_atomic_data (unsigned int atomic_number)
References atomic_data, and NUMBER_OF_ATOMS_IN_TABLE.
Referenced by AtomicBasisSet::print(), AtomicBasisSet::print_all(), and AtomicBasisSet::print_anal().
operator<<()
std::ostream & operator<< (std::ostream & s, const Atom & atom)
References Atom::atomic_number, Atom::q, Atom::x, Atom::y, and Atom::z.
smoothed_density()
static double smoothed_density (double r) static
Charge density corresponding to smoothed 1/r potential.
Invoke as rho(r/c)/c^3 where c is the radius of the smoothed volume.
References madness::nonlinear_vector_solver(), and madness::rsquared().
Referenced by MolecularEntity::nuclear_charge_density().
smoothed_potential()
static double smoothed_potential (double r) static
Regularized 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References e(), madness::nonlinear_vector_solver(), PI, and madness::r2().
Referenced by MolecularEntity::nuclear_attraction_potential(), and madness::PseudoNuclearCorrelationFactor::Spp_div_S().
smoothing_parameter()
static double smoothing_parameter (double Z, double eprec) static
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, e(), eprec, madness::nonlinear_vector_solver(), pow(), and Z.
Referenced by MolecularEntity::add_atom(), and madness::PseudoNuclearCorrelationFactor::Spp_div_S().
symbol_to_atomic_number()
unsigned int symbol_to_atomic_number (const std::string & symbol)
References atomic_data, madness::lowercase(), madness::nonlinear_vector_solver(), NUMBER_OF_ATOMS_IN_TABLE, and AtomicData::symbol_lowercase.
Referenced by MolecularEntity::read_file(), and AtomicBasisSet::read_file().
Variable Documentation
atomic_data
const AtomicData atomic_data[NUMBER_OF_ATOMS_IN_TABLE] static
Referenced by get_atomic_data(), MolecularEntity::print(), and symbol_to_atomic_number().
NUMBER_OF_ATOMS_IN_TABLE
const unsigned int NUMBER_OF_ATOMS_IN_TABLE = 110 static
Referenced by get_atomic_data(), and symbol_to_atomic_number().
PI
const double PI = 3.1415926535897932384 static
Referenced by smoothed_potential().