MADNESS: molecularsurface.cc File Reference
molecularsurface.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/sdf_shape_3D.h>
#include <madness/mra/funcplot.h>
#include "molecularmask.h"
#include <madness/constants.h>
#include <vector>
Macros
#define TIME(MSG, X)
Functions
double area_two_spheres (double r1, double r2, double d)
int main (int argc, char **argv)
double volume_two_spheres (double r1, double r2, double d)
Variables
double XXstart
Macro Definition Documentation
TIME
#define TIME (MSG, X)
Value:
                    XXstart=wall_time();         \
                    X; \
                    if (world.rank() == 0) print("timer:",MSG,"used",wall_time()-XXstart) \
Function Documentation
area_two_spheres()
double area_two_spheres (double r1, double r2, double d)
References d, madness::nonlinear_vector_solver(), madness::constants::pi, and madness::r2().
Referenced by main().
main()
int main (int argc, char ** argv)
References madness::_(), area_two_spheres(), SafeMPI::COMM_WORLD, d, madness::distance(), e(), madness::finalize(), madness::initialize(), k, L, madness::nonlinear_vector_solver(), madness::plotdx(), madness::plotpovray(), madness::print(), madness::r2(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), sigma, madness::startup(), thresh, TIME, and volume_two_spheres().
volume_two_spheres()
double volume_two_spheres (double r1, double r2, double d)
References d, madness::nonlinear_vector_solver(), madness::constants::pi, and madness::r2().
Referenced by main().
Variable Documentation
XXstart
double XXstart