MADNESS: oldtest.cc File Reference
oldtest.cc File Reference
Test code for Tensor, TensorIterator, SliceTensor, etc.
#include <madness/tensor/tensor.h>
#include <iostream>
#include <cstdio>
#include <complex>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <madness/world/print.h>
Typedefs
typedef std::complex< double > double_complex
typedef std::complex< float > float_complex
Functions
template<typename T , typename Q >
bool check (const T &t, const Q &q, double tol=1e-7)
void error (const char *msg, int code)
int main ()
template<typename T >
double mynorm (T x)
template<>
double mynorm< double_complex > (double_complex x)
template<>
double mynorm< float_complex > (float_complex x)
template<typename T , typename Q >
void Test1 ()
template<typename T >
void Test3 ()
template<class T >
void Test5 ()
template<class T >
void Test6 ()
template<>
void Test6a (Tensor< double_complex > &, long[])
template<>
void Test6a (Tensor< float_complex > &, long[])
template<class T >
void Test6a (Tensor< T > &f, long ind[])
template<class T >
void Test7 ()
template<class T >
void Test8 ()
Detailed Description
Test code for Tensor, TensorIterator, SliceTensor, etc.
Typedef Documentation
double_complex
typedef std::complex<double> double_complex
float_complex
typedef std::complex<float> float_complex
Function Documentation
check()
template<typename T , typename Q > bool check (const T & t, const Q & q, double tol = 1e-7) inline
References std::abs(), ok(), q(), and T().
Referenced by Test1(), Test5(), and Test7().
error()
void error (const char * msg, int code)
References madness::nonlinear_vector_solver().
Referenced by main(), main(), SafeMPI::Status::Set_error(), Test1(), Test5(), Test6(), Test6a(), and Test7().
main()
int main (void)
References a, madness::Tensor< T >::bounds_checking(), e(), error(), madness::f, madness::g, madness::nonlinear_vector_solver(), and madness::real().
mynorm()
template<typename T > double mynorm (T x)
Referenced by Test6().
mynorm< double_complex >()
template<> double mynorm< double_complex > (double_complex x)
mynorm< float_complex >()
template<> double mynorm< float_complex > (float_complex x)
Test1()
template<typename T , typename Q > void Test1 ()
References check(), d, madness::BaseTensor::dim(), e(), error(), madness::Tensor< T >::fillindex(), madness::Tensor< T >::fillrandom(), madness::BaseTensor::id(), IND1, IND2, IND3, IND4, IND5, IND6, ITERATOR1, ITERATOR2, ITERATOR3, ITERATOR4, ITERATOR5, ITERATOR6, madness::BaseTensor::ndim(), madness::nonlinear_vector_solver(), madness::BaseTensor::size(), madness::BaseTensor::stride(), and madness::tensor_type_names.
Test3()
template<typename T > void Test3 ()
References ITERATOR3, madness::nonlinear_vector_solver(), and madness::tensor_type_names.
Test5()
template<class T > void Test5 ()
References a, std::abs(), b, c, check(), madness::copy(), d, e(), error(), madness::f, madness::Tensor< T >::fillrandom(), IND5, ITERATOR5, madness::nonlinear_vector_solver(), T(), and madness::tensor_type_names.
Test6()
template<class T > void Test6 ()
References std::abs(), e(), error(), madness::f, madness::g, IND4, ITERATOR4, mynorm(), madness::nonlinear_vector_solver(), q(), T(), TENSOR_MAXDIM, madness::tensor_type_names, and Test6a().
Test6a() [1/3]
template<> void Test6a (Tensor< double_complex > & , long [])
Test6a() [2/3]
template<> void Test6a (Tensor< float_complex > & , long [])
Test6a() [3/3]
template<class T > void Test6a (Tensor< T > & f, long ind[])
References error(), madness::f, and T().
Referenced by Test6().
Test7()
template<class T > void Test7 ()
References std::abs(), c, check(), madness::copy(), dave(), e(), error(), madness::fast_transform(), madness::Tensor< T >::fill(), madness::Tensor< T >::fillrandom(), fred(), madness::inner(), ITERATOR2, ITERATOR4, ITERATOR6, k, madness::nonlinear_vector_solver(), madness::Tensor< T >::normf(), madness::outer(), madness::print(), q(), sum, madness::Tensor< T >::swapdim(), T(), madness::tensor_type_names, and madness::transform().
Test8()
template<class T > void Test8 ()