MADNESS: tdse1d.cc File Reference
tdse1d.cc File Reference
Example propagation of TDSE (translating atom) using various propagators.
#include <madness/mra/mra.h>
#include <madness/mra/qmprop.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
#include <string>
Classes
struct refop
struct unaryexp< T, NDIM >
Macros
#define MAKE_PROPAGATOR(world, t) qm_1d_free_particle_propagator(k, c, t, 2.0*L)
#define NO_GENTENSOR
Typedefs
typedef Convolution1D< double_complex > complex_operatorT
typedef std::shared_ptr< complex_operatorT > pcomplex_operatorT
Functions
complex_function_1d APPLY (complex_operatorT *q1d, const complex_function_1d &psi)
double atom_position ()
double dVsq (const coord_1d &r)
complex_function_1d expV (World &world, double vcoeff, double dcoeff)
double icoeff (const int np, const int j, const double t)
int main (int argc, char **argv)
template<typename T >
T myp (const std::vector< T > &ps, const double t)
void print_info (World &world, const complex_function_1d &psi, int step)
double_complex psi_exact (const coord_1d &r)
complex_function_1d q_c (World &world, const int np, const complex_function_1d psi0, const double tstep)
static void readin (int np)
complex_function_1d sympgrad4 (World &world, const complex_function_1d &psi0, const double tstep, const double xi, const double chi)
complex_function_1d sympgrad6 (World &world, const complex_function_1d &psi0, const double tstep)
complex_function_1d trotter (World &world, const complex_function_1d &psi0, const double tstep, complex_operatorT *G0=0)
double V (const coord_1d &r)
Variables
Tensor< double > B
static double c = 1.86*ctarget
static double ctarget = 20.0
static double current_time = 0.0
static const double energy_exact = -6.188788775728796797594788
static const double eshift = 0.0
double fix_iter_tol = thresh*10.0
pcomplex_operatorT G
std::vector< pcomplex_operatorT > Gs
std::vector< pcomplex_operatorT > Gss
std::vector< pcomplex_operatorT > Gtrs
static const double_complex I = double_complex(0,1)
static const long k = 20
static const double L = 100.0
const int maxiter = 20
int np
Tensor< double > tc
static double tcrit = 2*constants::pi/(c*c)
static const double thresh = 1e-12
static const double velocity = 3.0
static const double x0 = -L + 10.0
Detailed Description
Example propagation of TDSE (translating atom) using various propagators.
Macro Definition Documentation
MAKE_PROPAGATOR
#define MAKE_PROPAGATOR (world, t) qm_1d_free_particle_propagator(k, c, t, 2.0*L)
NO_GENTENSOR
#define NO_GENTENSOR
Typedef Documentation
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
pcomplex_operatorT
typedef std::shared_ptr<complex_operatorT> pcomplex_operatorT
Function Documentation
APPLY()
complex_function_1d APPLY (complex_operatorT * q1d, const complex_function_1d & psi)
References madness::apply_1d_realspace_push(), madness::nonlinear_vector_solver(), psi(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::sum_down().
Referenced by q_c(), sympgrad4(), sympgrad6(), and trotter().
atom_position()
double atom_position ()
References current_time, velocity, and x0.
Referenced by dVsq(), print_info(), print_info(), psi_exact(), and V().
dVsq()
double dVsq (const coord_1d & r)
References atom_position(), and madness::nonlinear_vector_solver().
Referenced by expV().
expV()
complex_function_1d expV (World & world, double vcoeff, double dcoeff)
References madness::Function< T, NDIM >::compress(), d, dVsq(), expV(), madness::nonlinear_vector_solver(), potn(), madness::Function< T, NDIM >::scale(), madness::Function< T, NDIM >::truncate(), madness::Function< T, NDIM >::unaryop(), and V().
Referenced by chin_chen(), converge(), expV(), make_exp(), make_exp(), propagate(), propagate(), propagate(), sympgrad4(), sympgrad6(), test_chin_chen(), test_trotter(), trotter(), trotter(), trotter(), trotter(), and trotter().
icoeff()
double icoeff (const int np, const int j, const double t)
References madness::nonlinear_vector_solver(), np, and tc.
Referenced by myp().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::broadcast(), SafeMPI::COMM_WORLD, current_time, exact, madness::finalize(), madness::World::gop, Gs, Gss, Gtrs, madness::initialize(), k, L, lo, MAKE_PROPAGATOR, madness::nonlinear_vector_solver(), np, madness::plot_line(), madness::print(), print_info(), psi(), psi_exact(), q_c(), madness::World::rank(), readin(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), sympgrad4(), sympgrad6(), tc, tcrit, thresh, trotter(), madness::Function< T, NDIM >::truncate(), tstep, velocity, and x0.
myp()
template<typename T > T myp (const std::vector< T > & ps, const double t)
References icoeff(), madness::nonlinear_vector_solver(), np, p(), madness::BaseTensor::size(), and T().
Referenced by q_c().
print_info()
void print_info (World & world, const complex_function_1d & psi, int step)
References atom_position(), current_time, madness::inner(), madness::nonlinear_vector_solver(), norm(), madness::norm2(), potn(), psi(), psi_exact(), madness::World::rank(), and V().
Referenced by main().
psi_exact()
double_complex psi_exact (const coord_1d & r)
References madness::arg(), atom_position(), current_time, energy_exact, eshift, madness::nonlinear_vector_solver(), psi(), and velocity.
Referenced by main(), and print_info().
q_c()
complex_function_1d q_c (World & world, const int np, const complex_function_1d psi0, const double tstep)
References APPLY(), madness::Function< T, NDIM >::compress(), madness::compress(), current_time, fix_iter_tol, madness::gaxpy(), Gs, Gss, Gtrs, I, k, maxiter, myp(), madness::nonlinear_vector_solver(), madness::response_space::norm2(), madness::norm2(), np, psi0(), madness::World::rank(), madness::scale(), madness::sub(), tc, thresh, trotter(), madness::Function< T, NDIM >::truncate(), tstep, and V().
Referenced by main().
readin()
static void readin (int np) static
References madness::gauss_legendre(), madness::nonlinear_vector_solver(), np, and tc.
Referenced by main().
sympgrad4()
complex_function_1d sympgrad4 (World & world, const complex_function_1d & psi0, const double tstep, const double xi, const double chi)
References APPLY(), current_time, expV(), lambda, MAKE_PROPAGATOR, madness::nonlinear_vector_solver(), psi(), psi0(), madness::Function< T, NDIM >::truncate(), tstep, and xi.
Referenced by main().
sympgrad6()
complex_function_1d sympgrad6 (World & world, const complex_function_1d & psi0, const double tstep)
References APPLY(), current_time, expV(), lambda, MAKE_PROPAGATOR, mu, madness::nonlinear_vector_solver(), psi(), psi0(), madness::Function< T, NDIM >::truncate(), and tstep.
Referenced by main().
trotter()
complex_function_1d trotter (World & world, const complex_function_1d & psi0, const double tstep, complex_operatorT * G0 = 0)
References APPLY(), current_time, expV(), G0, MAKE_PROPAGATOR, psi(), psi0(), madness::Function< T, NDIM >::truncate(), and tstep.
Referenced by main(), and q_c().
V()
double V (const coord_1d & r)
References atom_position(), eshift, and madness::nonlinear_vector_solver().
Referenced by expV(), print_info(), and q_c().
Variable Documentation
B
Tensor<double> B
c
double c = 1.86*ctarget static
ctarget
double ctarget = 20.0 static
Referenced by propagate(), propagate(), propagate(), and test_qm().
current_time
double current_time = 0.0 static
Referenced by atom_position(), atom_position(), madness::ThreadPool::await(), main(), madness::CCTimer::print(), print_info(), print_info(), psi_exact(), q_c(), sympgrad4(), sympgrad6(), and trotter().
energy_exact
const double energy_exact = -6.188788775728796797594788 static
Referenced by main(), and psi_exact().
eshift
const double eshift = 0.0 static
Referenced by madness::Solver< T, NDIM >::do_rhs(), madness::Solver< T, NDIM >::do_rhs_simple(), psi_exact(), and V().
fix_iter_tol
double fix_iter_tol = thresh*10.0
Referenced by q_c().
G
pcomplex_operatorT G
Gs
std::vector<pcomplex_operatorT> Gs
Referenced by main(), and q_c().
Gss
std::vector<pcomplex_operatorT> Gss
Referenced by main(), and q_c().
Gtrs
std::vector<pcomplex_operatorT> Gtrs
Referenced by main(), and q_c().
I
const double_complex I = double_complex(0,1) static
Referenced by KPeriodicBSHOperator::KPeriodicBSHOperator(), KPeriodicBSHOperator::KPeriodicBSHOperator(), apply_periodic_bsh(), apply_potential(), madness::check_tuple_is_valid_task_result(), madness::MP3::compute_mp3_ghij(), fixphases(), fixphases(), madness::get_index_of_first_vector_argument(), kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), make_basis(), madness::Zcis::make_CIS_matrix(), madness::TDHF::make_cis_matrix(), madness::Zcis::make_guess(), madness::TDHF::make_guess_from_initial_diagonalization(), make_kinetic_matrix(), madness::Solver< T, NDIM >::make_kinetic_matrix(), make_kinetic_matrix(), makeao(), madness::Localizer::matrix_exponential(), madness::Molecule::moment_of_inertia(), AtomicBasisFunctor< Q >::operator()(), madness::WSTAtomicBasisFunctor::operator()(), madness::Molecule::orient(), projector_external_dof(), madness::MolecularOptimizer::projector_external_dof(), and q_c().
k
const long k = 20 static
Referenced by main(), and q_c().
L
const double L = 100.0 static
Referenced by main().
maxiter
const int maxiter = 20
Referenced by q_c().
np
int np
Referenced by SafeMPI::Intracomm::binary_tree_info(), DF::diagonalize(), icoeff(), main(), myp(), ContractedGaussianShell::normalize(), madness::ContractedGaussianShell::normalize(), madness::FunctionImpl< T, NDIM >::phi_for_mul(), q_c(), and readin().
tc
Tensor<double> tc
Referenced by icoeff(), madness::CC2::iterate_lrcc2_pairs(), main(), q_c(), readin(), and tensor_to_numpy().
tcrit
double tcrit = 2*constants::pi/(c*c) static
Referenced by main(), madness::BandlimitedPropagator::plot(), propagate(), propagate(), propagate(), test_chin_chen(), test_qm(), and test_trotter().
thresh
const double thresh = 1e-12 static
Referenced by main(), and q_c().
velocity
const double velocity = 3.0 static
Referenced by atom_position(), main(), and psi_exact().
x0
const double x0 = -L + 10.0 static
Referenced by atom_position(), beta_func(), distancesq(), main(), and madness::GaussianConvolution1D< Q >::rnlp().