MADNESS: test_lattice.cc File Reference
test_lattice.cc File Reference
#include <madness/mra/mra.h>
#include "poperator.h"
Classes
class wstFunctor< Q >
Typedefs
typedef Vector< double, 1 > coordT1d
typedef Vector< double, 3 > coordT3d
Functions
static std::complex< double > complex_exp_1d (const coordT1d r)
static double func_ones (const coordT3d &r)
template<typename Q , int NDIM>
Q laplacian (const Q &f, bool periodic=false)
int main (int argc, char **argv)
static double phi_bsh_func3d (const coordT3d &r)
static double_complex phi_coulomb_func3d (const coordT3d &r)
static double rho_bsh_func3d (const coordT3d &r)
static double_complex rho_coulomb_func3d (const coordT3d &r)
static double rho_gaussian_func3d (const coordT3d &r)
void testPeriodicCoulomb3d (int argc, char **argv)
Variables
const double L = 15.0
const double N = 2.0
Typedef Documentation
coordT1d
typedef Vector<double,1> coordT1d
coordT3d
typedef Vector<double,3> coordT3d
Function Documentation
complex_exp_1d()
static std::complex< double > complex_exp_1d (const coordT1d r) static
References L, N, madness::nonlinear_vector_solver(), and WST_PI.
func_ones()
static double func_ones (const coordT3d & r) static
laplacian()
template<typename Q , int NDIM> Q laplacian (const Q & f, bool periodic = false)
References madness::___, diff(), madness::f, madness::FunctionDefaults< NDIM >::get_bc(), NDIM, madness::nonlinear_vector_solver(), Q(), and madness::FunctionDefaults< NDIM >::set_bc().
main()
int main (int argc, char ** argv)
References madness::BC_PERIODIC, madness::FunctionDefaults< NDIM >::set_bc(), and testPeriodicCoulomb3d().
phi_bsh_func3d()
static double phi_bsh_func3d (const coordT3d & r) static
References L, madness::nonlinear_vector_solver(), twopi, and WST_PI.
phi_coulomb_func3d()
static double_complex phi_coulomb_func3d (const coordT3d & r) static
References L, N, madness::nonlinear_vector_solver(), and WST_PI.
Referenced by testPeriodicCoulomb3d().
rho_bsh_func3d()
static double rho_bsh_func3d (const coordT3d & r) static
References L, madness::nonlinear_vector_solver(), twopi, and WST_PI.
rho_coulomb_func3d()
static double_complex rho_coulomb_func3d (const coordT3d & r) static
References L, N, madness::nonlinear_vector_solver(), and WST_PI.
Referenced by testPeriodicCoulomb3d().
rho_gaussian_func3d()
static double rho_gaussian_func3d (const coordT3d & r) static
References madness::nonlinear_vector_solver(), pow(), and WST_PI.
testPeriodicCoulomb3d()
void testPeriodicCoulomb3d (int argc, char ** argv)
References madness::abs(), madness::apply(), SafeMPI::COMM_WORLD, e(), madness::error(), SafeMPI::Finalize(), madness::FunctionDefaults< NDIM >::get_cell_width(), SafeMPI::Init(), k, L, madness::nonlinear_vector_solver(), op(), p(), phi_coulomb_func3d(), madness::plotdx(), rho_coulomb_func3d(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), thresh, and madness::Function< T, NDIM >::truncate().
Referenced by main().
Variable Documentation
L
const double L = 15.0
Referenced by complex_exp_1d(), phi_bsh_func3d(), phi_coulomb_func3d(), rho_bsh_func3d(), rho_coulomb_func3d(), and testPeriodicCoulomb3d().
N
const double N = 2.0
Referenced by complex_exp_1d(), phi_coulomb_func3d(), and rho_coulomb_func3d().