MADNESS: test_be.cc File Reference
test_be.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include "dft.h"
#include "hartreefock.h"
Macros
#define TO_STRING(s) TO_STRING2(s)
#define TO_STRING2(s) #s
Typedefs
typedef Vector< double, 3 > coordT
Functions
int main (int argc, char **argv)
static double psi_func_be1 (const coordT &rr)
static double psi_func_be2 (const coordT &rr)
static double rho_func_be (const coordT &rr)
static double smoothed_potential (double r)
Regularized 1/r potential.
static double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
void test_hf_be (World &world)
static double V_func_be (const coordT &r)
Variables
const double PI = 3.1415926535897932384
Macro Definition Documentation
TO_STRING
#define TO_STRING (s) TO_STRING2(s)
TO_STRING2
#define TO_STRING2 (s) #s
Typedef Documentation
coordT
typedef Vector<double,3> coordT
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), SafeMPI::Finalize(), madness::BaseTensor::get_instance_count(), madness::World::gop, SafeMPI::Init(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::World::size(), madness::startup(), test_hf_be(), and TO_STRING.
psi_func_be1()
static double psi_func_be1 (const coordT & rr) static
References e(), and madness::nonlinear_vector_solver().
Referenced by test_hf_be().
psi_func_be2()
static double psi_func_be2 (const coordT & rr) static
References madness::nonlinear_vector_solver().
Referenced by test_hf_be().
rho_func_be()
static double rho_func_be (const coordT & rr) static
References c, and madness::nonlinear_vector_solver().
Referenced by test_hf_be().
smoothed_potential()
static double smoothed_potential (double r) static
Regularized 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References e(), madness::nonlinear_vector_solver(), PI, and madness::r2().
Referenced by V_func_be().
smoothing_parameter()
static double smoothing_parameter (double Z, double eprec) static
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, e(), eprec, madness::nonlinear_vector_solver(), pow(), and Z.
Referenced by V_func_be().
test_hf_be()
void test_hf_be (World & world)
References madness::apply(), e(), madness::error(), L, madness::nonlinear_vector_solver(), op(), p(), madness::ElectronicStructureParams::periodic, madness::print(), psi_func_be1(), psi_func_be2(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), rho_func_be(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), thresh, madness::Function< T, NDIM >::thresh(), V_func_be(), and vnuc().
Referenced by main().
V_func_be()
static double V_func_be (const coordT & r) static
References c, e(), madness::nonlinear_vector_solver(), smoothed_potential(), and smoothing_parameter().
Referenced by test_hf_be().
Variable Documentation
PI
const double PI = 3.1415926535897932384
Referenced by smoothed_potential().