MADNESS: test_keybox.cc File Reference
test_keybox.cc File Reference
Tests for Key::is_neighbor_of(simpt, bperiodic) — the geometric replacement for the legacy simpt2key(simpt, n).is_neighbor_of(*this, bperiodic) idiom.
#include <madness/mra/mra.h>
#include <madness/mra/funcdefaults.h>
#include <madness/mra/key.h>
#include <madness/world/test_utilities.h>
Functions
int main (int argc, char **argv)
Detailed Description
Tests for Key::is_neighbor_of(simpt, bperiodic) — the geometric replacement for the legacy simpt2key(simpt, n).is_neighbor_of(*this, bperiodic) idiom.
Function Documentation
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), and madness::startup().