MADNESS: testvmra.cc File Reference
testvmra.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/vmra.h>
#include <madness/misc/ran.h>
#include <madness/world/test_utilities.h>
Classes
class Gaussian< T, NDIM >
struct many_to_many_op< NDIM >
struct to test the multi_to_multi_op_values
Macros
#define END_TIMER(msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
#define NO_GENTENSOR
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
Functions
template<typename T >
T complexify (T c)
template<>
double_complex complexify< double_complex > (double_complex c)
template<>
float_complex complexify< float_complex > (float_complex c)
int main (int argc, char **argv)
template<typename T , std::size_t NDIM>
Gaussian< T, NDIM > * RandomGaussian (const Tensor< double > cell, double expntmax=1e5)
Makes a square-normalized Gaussian with random origin and exponent.
template<typename T , std::size_t NDIM>
void test_add (World &world)
template<typename T , typename R , int NDIM>
void test_cross (World &world)
template<typename T , typename R , int NDIM, bool sym>
void test_dot (World &world)
template<typename T , typename R , int NDIM, bool sym>
void test_inner (World &world)
template<typename T , int NDIM>
void test_matrix_mul_sparse (World &world)
template<std::size_t NDIM>
void test_multi_to_multi_op (World &world)
template<typename T , int NDIM>
void test_orthonormalize_canonical (World &world)
template<typename T , int NDIM>
void test_orthonormalize_symmetric (World &world)
template<typename T , int NDIM>
void test_rot (World &world)
template<typename T , std::size_t NDIM>
int test_transform (World &world)
Variables
const double PI = 3.1415926535897932384
double sss
double ttt
Macro Definition Documentation
END_TIMER
#define END_TIMER (msg) ttt=wall_time()-ttt; sss=cpu_time()-sss; if (world.rank()==0) printf("timer: %20.20s %8.2fs %8.2fs\n", msg, sss, ttt)
NO_GENTENSOR
#define NO_GENTENSOR
START_TIMER
#define START_TIMER world.gop.fence(); ttt=wall_time(); sss=cpu_time()
Function Documentation
complexify()
template<typename T > T complexify (T c)
References c.
complexify< double_complex >()
template<> double_complex complexify< double_complex > (double_complex c)
References c.
complexify< float_complex >()
template<> float_complex complexify< float_complex > (float_complex c)
References c.
main()
int main (int argc, char ** argv)
References madness::cpu_time(), madness::default_random_generator, e(), madness::error(), madness::finalize(), madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), madness::Random::setstate(), smalltest, and madness::startup().
RandomGaussian()
template<typename T , std::size_t NDIM> Gaussian< T, NDIM > * RandomGaussian (const Tensor< double > cell, double expntmax = 1e5)
Makes a square-normalized Gaussian with random origin and exponent.
References lo, NDIM, madness::nonlinear_vector_solver(), PI, pow(), madness::RandomValue< double >(), and T().
test_add()
template<typename T , std::size_t NDIM> void test_add (World & world)
References diff(), madness::inner(), MADNESS_CHECK, NDIM, madness::nonlinear_vector_solver(), madness::norm2(), madness::print(), madness::r2(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), sum, and thresh.
test_cross()
template<typename T , typename R , int NDIM> void test_cross (World & world)
References madness::compress(), madness::cross(), END_TIMER, madness::f, MADNESS_CHECK, NDIM, madness::nonlinear_vector_solver(), madness::norm2(), madness::print(), R, madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, T(), TENSOR_RESULT_TYPE, and thresh.
test_dot()
template<typename T , typename R , int NDIM, bool sym> void test_dot (World & world)
References madness::compress(), END_TIMER, madness::f, MADNESS_CHECK, madness::matrix_dot(), madness::matrix_dot_old(), NDIM, madness::nonlinear_vector_solver(), madness::print(), R, madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, T(), TENSOR_RESULT_TYPE, and thresh.
test_inner()
template<typename T , typename R , int NDIM, bool sym> void test_inner (World & world)
References madness::compress(), END_TIMER, madness::f, MADNESS_CHECK, madness::matrix_inner(), madness::matrix_inner_old(), NDIM, madness::nonlinear_vector_solver(), madness::print(), R, madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, T(), TENSOR_RESULT_TYPE, and thresh.
test_matrix_mul_sparse()
template<typename T , int NDIM> void test_matrix_mul_sparse (World & world)
References END_TIMER, madness::f, MADNESS_CHECK, NDIM, madness::nonlinear_vector_solver(), madness::norm2(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, and thresh.
test_multi_to_multi_op()
template<std::size_t NDIM> void test_multi_to_multi_op (World & world)
References madness::error(), madness::f, MADNESS_CHECK, madness::multi_to_multi_op_values(), NDIM, madness::nonlinear_vector_solver(), madness::norm2(), op(), madness::print(), madness::World::rank(), madness::refine_to_common_level(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), and thresh.
test_orthonormalize_canonical()
template<typename T , int NDIM> void test_orthonormalize_canonical (World & world)
References madness::compress(), e(), END_TIMER, madness::f, MADNESS_CHECK, madness::matrix_inner(), NDIM, madness::nonlinear_vector_solver(), madness::orthonormalize_canonical(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, test(), and thresh.
test_orthonormalize_symmetric()
template<typename T , int NDIM> void test_orthonormalize_symmetric (World & world)
References madness::compress(), e(), END_TIMER, madness::f, MADNESS_CHECK, madness::matrix_inner(), NDIM, madness::nonlinear_vector_solver(), madness::orthonormalize_symmetric(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, test(), and thresh.
test_rot()
template<typename T , int NDIM> void test_rot (World & world)
References madness::compress(), madness::div(), END_TIMER, madness::f, madness::grad(), NDIM, madness::nonlinear_vector_solver(), madness::norm2(), madness::print(), madness::World::rank(), rot, madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, and thresh.
test_transform()
template<typename T , std::size_t NDIM> int test_transform (World & world)
References c, madness::change_tree_state(), madness::compressed, END_TIMER, madness::f, madness::WorldGopInterface::fence(), madness::World::gop, MADNESS_CHECK, NDIM, madness::nonlinear_vector_solver(), madness::norm2(), madness::print(), madness::RandomValue< int >(), madness::reconstructed, madness::redundant_after_merge, madness::FunctionDefaults< NDIM >::set_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), START_TIMER, thresh, madness::transform(), and madness::transform_reconstructed().
Variable Documentation
PI
const double PI = 3.1415926535897932384
Referenced by RandomGaussian().
sss
double sss
ttt
double ttt