MADNESS: test_xc.cc File Reference
test_xc.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include "libxc.h"
Macros
#define TO_STRING(s) TO_STRING2(s)
#define TO_STRING2(s) #s
Typedefs
typedef Vector< double, 3 > coordT
Functions
void add_op (const Key< 3 > &key, Tensor< double > tcube, Tensor< double > lcube, Tensor< double > rcube)
static void da_ldaop (const Key< 3 > &key, Tensor< double > &t)
static double gauss_func1 (const coordT &r)
static double gauss_func3 (const coordT &r)
int main (int argc, char **argv)
void multiply_op (const Key< 3 > &key, Tensor< double > tcube, Tensor< double > lcube, Tensor< double > rcube)
void test_xc1 (World &world)
void test_xc2 (World &world)
Variables
const double PI = 3.1415926535897932384
Macro Definition Documentation
TO_STRING
#define TO_STRING (s) TO_STRING2(s)
TO_STRING2
#define TO_STRING2 (s) #s
Typedef Documentation
coordT
typedef Vector<double,3> coordT
Function Documentation
add_op()
void add_op (const Key< 3 > & key, Tensor< double > tcube, Tensor< double > lcube, Tensor< double > rcube)
References madness::nonlinear_vector_solver(), and TERNARY_OPTIMIZED_ITERATOR.
Referenced by test_xc2().
da_ldaop()
static void da_ldaop (const Key< 3 > & key, Tensor< double > & t) static
References madness::c_rks_vwn5__(), madness::munge(), madness::nonlinear_vector_solver(), q(), UNARY_OPTIMIZED_ITERATOR, and madness::x_rks_s__().
Referenced by test_xc2().
gauss_func1()
static double gauss_func1 (const coordT & r) static
References madness::nonlinear_vector_solver().
Referenced by test_xc2().
gauss_func3()
static double gauss_func3 (const coordT & r) static
[1] F. Bloch, Zeitschrift fuer Physik, Vol. 57 (1929) 545. *‍/* Parameters: *‍/* --------------------------------------------------------------------— *‍/* [1] F. Bloch, Zeitschrift fuer Physik, Vol. 57 (1929) 545. *‍/* Parameters: *‍/* Parameters: *‍/* VWN interpolation parameters *‍/* paramagnetic *‍/* t4 = (1/(4/3)*pi)**(1/3) *‍/* t5 = 0.5/(2**(1/3)-1) *‍/* t6 = 2/(3*(2**(1/3)-1)) *‍/* t7 = 2.25*(2**(1/3)-1) *‍/* Paramagnetic interpolation constants *‍/* closed shell case *‍/* paramagnetic *‍/* corrected b1->b2 ps Apr98 *‍/* --------------------------------------------------------------------— *‍/* Parameters: *‍/* VWN interpolation parameters *‍/* spin stiffness *‍/* paramagnetic *‍/* t4 = (1/(4/3)*pi)**(1/3) *‍/* t5 = 0.5/(2**(1/3)-1) *‍/* t6 = 2/(3*(2**(1/3)-1)) *‍/* t7 = 2.25*(2**(1/3)-1) *‍/* Spin stiffness interpolation constants *‍/* Paramagnetic interpolation constants *‍/* Ferromagnetic interpolation constants *‍/* try nwchem values *‍/* Interpolation intervals *‍/* open shell case *‍/* spin-stiffness *‍/* paramagnetic *‍/* corrected b1->b2 ps Apr98 *‍/* ferromagnetic *‍/* polarisation function *‍/
References madness::nonlinear_vector_solver().
Referenced by test_xc2().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::BaseTensor::get_instance_count(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::World::size(), madness::startup(), test_xc2(), and TO_STRING.
multiply_op()
void multiply_op (const Key< 3 > & key, Tensor< double > tcube, Tensor< double > lcube, Tensor< double > rcube)
References madness::nonlinear_vector_solver(), and TERNARY_OPTIMIZED_ITERATOR.
Referenced by test_xc2().
test_xc1()
void test_xc1 (World & world)
References madness::c_rks_vwn5__(), k, madness::nonlinear_vector_solver(), pow(), and madness::x_rks_s__().
test_xc2()
void test_xc2 (World & world)
References add_op(), madness::binary_op(), madness::copy(), da_ldaop(), e(), madness::f, f2, gauss_func1(), gauss_func3(), L, multiply_op(), madness::nonlinear_vector_solver(), p(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), sum, and thresh.
Referenced by main().
Variable Documentation
PI
const double PI = 3.1415926535897932384