MADNESS: test_coulomb.cc File Reference
test_coulomb.cc File Reference
#include <madness/mra/mra.h>
#include <madness/constants.h>
#include "eigsolver.h"
#include "dft.h"
Macros
#define DEBUG_STREAM std::cout
#define LOG_STREAM std::cout
#define WST_PI madness::constants::pi
Typedefs
typedef Vector< double, 1 > coordT1d
typedef Vector< double, 3 > coordT3d
Functions
template<int NDIM>
static double gaussian_func (const Vector< double, NDIM > r)
int main (int argc, char **argv)
static double phi_initial_guess1D (const coordT1d &r)
static double phi_initial_guess3D (const coordT3d &r)
static double psi_func_he (const coordT3d &r)
static double smoothed_potential (double r)
Regularized 1/r potential.
static double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
void test_he (int argc, char **argv)
static double V_cosine1D (const coordT1d &r)
static double V_cosine3D (const coordT3d &r)
static double V_cosine3D_sep (const coordT3d &r)
static double V_func_he (const coordT3d &r)
Variables
const double alpha = 4.5
const double L = 30.0
Macro Definition Documentation
DEBUG_STREAM
#define DEBUG_STREAM std::cout
LOG_STREAM
#define LOG_STREAM std::cout
WST_PI
#define WST_PI madness::constants::pi
Typedef Documentation
coordT1d
typedef Vector<double,1> coordT1d
coordT3d
typedef Vector<double,3> coordT3d
Function Documentation
gaussian_func()
template<int NDIM> static double gaussian_func (const Vector< double, NDIM > r) static
References L, NDIM, madness::nonlinear_vector_solver(), and sum.
main()
int main (int argc, char ** argv)
phi_initial_guess1D()
static double phi_initial_guess1D (const coordT1d & r) static
References madness::nonlinear_vector_solver().
phi_initial_guess3D()
static double phi_initial_guess3D (const coordT3d & r) static
References L, madness::nonlinear_vector_solver(), twopi, and WST_PI.
psi_func_he()
static double psi_func_he (const coordT3d & r) static
References e(), and madness::nonlinear_vector_solver().
Referenced by test_he().
smoothed_potential()
static double smoothed_potential (double r) static
Regularized 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References e(), madness::nonlinear_vector_solver(), madness::r2(), and WST_PI.
Referenced by V_func_he().
smoothing_parameter()
static double smoothing_parameter (double Z, double eprec) static
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, e(), eprec, madness::nonlinear_vector_solver(), pow(), and Z.
Referenced by V_func_he().
test_he()
void test_he (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), SafeMPI::Finalize(), SafeMPI::Init(), L, LOG_STREAM, madness::nonlinear_vector_solver(), psi(), psi_func_he(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), thresh, madness::Function< T, NDIM >::thresh(), and V_func_he().
V_cosine1D()
static double V_cosine1D (const coordT1d & r) static
References alpha, L, madness::nonlinear_vector_solver(), twopi, and WST_PI.
V_cosine3D()
static double V_cosine3D (const coordT3d & r) static
References alpha, L, madness::nonlinear_vector_solver(), twopi, and WST_PI.
V_cosine3D_sep()
static double V_cosine3D_sep (const coordT3d & r) static
References alpha, L, madness::nonlinear_vector_solver(), twopi, and WST_PI.
V_func_he()
static double V_func_he (const coordT3d & r) static
References c, e(), madness::nonlinear_vector_solver(), smoothed_potential(), and smoothing_parameter().
Referenced by test_he().
Variable Documentation
alpha
const double alpha = 4.5
Referenced by V_cosine1D(), V_cosine3D(), and V_cosine3D_sep().
L
const double L = 30.0
Referenced by gaussian_func(), phi_initial_guess3D(), test_he(), V_cosine1D(), V_cosine3D(), and V_cosine3D_sep().