MADNESS: testspectralprop.cc File Reference
testspectralprop.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include <vector>
#include "spectralprop.h"
#include <madness/mra/qmprop.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Classes
class Fred
Wrapper around vector demonstrating interface necessary.
class PsiExact
class Vnuclear
Namespaces
namespace madness
Namespace for all elements and tools of MADNESS.
Typedefs
typedef Convolution1D< double_complex > complex_operatorT
typedef std::shared_ptr< complex_operatorT > pcomplex_operatorT
Functions
complex_function_1d APPLY (complex_operatorT *q1d, const complex_function_1d &psi)
complex_function_1d applyexpLt (double dt, const complex_function_1d &u)
complex_function_1d applyN (double t, const complex_function_1d &u)
double atom_position (double current_time)
double madness::distance (const Fred &a, const Fred &b)
double madness::distance (madness::Function< std::complex< double >, 1ul > &a, madness::Function< std::complex< double >, 1ul > &b)
double exact (double t, double u0)
Fred expL (double dt, const Fred &f)
double expL_double (double dt, double u)
template<typename T >
std::pair< bool, T > find_fuzzy (double t, const std::vector< std::pair< double, T > > &cache)
complex_operatorT * G (World &world, double dt)
int main (int argc, char **argv)
complex_operatorT * MAKE_PROPAGATOR (World &world, double t)
Fred N (double t, const Fred &f)
double N_double (double t, const double u)
std::ostream & operator<< (std::ostream &s, const Fred &f)
void print_info (World &world, double current_time, const complex_function_1d &psi, int step)
void test0 (World &world)
void test0GaussLobatto (World &world)
void test1 (World &world)
void test2 (World &world)
real_function_1d vnuc (World &world, double t)
Variables
static double c = 1.86*ctarget
static double ctarget = 20.0
static const double energy_exact = -6.188788775728796797594788
static const double eshift = 0.0
static std::vector< std::pair< double, complex_operatorT * > > G_cache
static const long k = 12
static const double L = 100.0
static double tcrit = 2*constants::pi/(c*c)
static const double thresh = 1e-8
static const double velocity = 3.0
std::vector< std::pair< double, real_function_1d > > vnuc_cache
static const double x0 = -L + 10.0
Typedef Documentation
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
pcomplex_operatorT
typedef std::shared_ptr<complex_operatorT> pcomplex_operatorT
Function Documentation
APPLY()
complex_function_1d APPLY (complex_operatorT * q1d, const complex_function_1d & psi)
References madness::apply_1d_realspace_push(), madness::nonlinear_vector_solver(), psi(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::sum_down().
Referenced by applyexpLt().
applyexpLt()
complex_function_1d applyexpLt (double dt, const complex_function_1d & u)
References APPLY(), madness::copy(), e(), madness::Function< T, NDIM >::truncate(), and u().
Referenced by test2().
applyN()
complex_function_1d applyN (double t, const complex_function_1d & u)
conj(u)*u
References madness::Function< T, NDIM >::truncate(), u(), and vnuc().
Referenced by test2().
atom_position()
double atom_position (double current_time)
References current_time, velocity, and x0.
exact()
double exact (double t, double u0)
References madness::nonlinear_vector_solver().
expL()
Fred expL (double dt, const Fred & f)
References madness::f, madness::nonlinear_vector_solver(), and Fred::set().
Referenced by madness::SpectralPropagator::solve(), madness::SpectralPropagatorGaussLobatto::step(), madness::SpectralPropagator::step(), and test1().
expL_double()
double expL_double (double dt, double u)
References madness::nonlinear_vector_solver(), and u().
Referenced by test0(), and test0GaussLobatto().
find_fuzzy()
template<typename T > std::pair< bool, T > find_fuzzy (double t, const std::vector< std::pair< double, T > > & cache)
References madness::cache, e(), madness::nonlinear_vector_solver(), and T().
Referenced by G(), and vnuc().
G()
complex_operatorT * G (World & world, double dt)
References find_fuzzy(), G_cache, MAKE_PROPAGATOR, and p().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::finalize(), madness::initialize(), madness::print(), madness::startup(), test0(), test0GaussLobatto(), test1(), and test2().
MAKE_PROPAGATOR()
complex_operatorT * MAKE_PROPAGATOR (World & world, double t)
References c, k, L, and madness::qm_1d_free_particle_propagator().
N()
Fred N (double t, const Fred & f)
References madness::f, and Fred::set().
N_double()
double N_double (double t, const double u)
References u().
Referenced by test0(), and test0GaussLobatto().
operator<<()
std::ostream & operator<< (std::ostream & s, const Fred & f)
References madness::f.
print_info()
void print_info (World & world, double current_time, const complex_function_1d & psi, int step)
References atom_position(), current_time, madness::inner(), madness::nonlinear_vector_solver(), norm(), potn(), psi(), madness::World::rank(), and vnuc().
Referenced by test2().
test0()
void test0 (World & world)
References exact, expL_double(), N_double(), madness::nonlinear_vector_solver(), P, madness::print(), madness::World::rank(), and u().
Referenced by main().
test0GaussLobatto()
void test0GaussLobatto (World & world)
References e(), exact, expL_double(), N_double(), madness::nonlinear_vector_solver(), P, madness::print(), madness::World::rank(), and u().
Referenced by main().
test1()
void test1 (World & world)
References exact, expL(), N, madness::nonlinear_vector_solver(), P, madness::print(), madness::World::rank(), and u().
Referenced by madness::F12Potentials::F12Potentials(), and main().
test2()
void test2 (World & world)
References applyexpLt(), applyN(), madness::WorldGopInterface::broadcast(), madness::copy(), energy_exact, madness::World::gop, madness::inner(), k, L, madness::nonlinear_vector_solver(), P, madness::print(), print_info(), psi(), psi0(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), tcrit, thresh, madness::Function< T, NDIM >::truncate(), tstep, velocity, vnuc_cache, and x0.
Referenced by madness::F12Potentials::F12Potentials(), and main().
vnuc()
real_function_1d vnuc (World & world, double t)
References find_fuzzy(), vnuc(), and vnuc_cache.
Referenced by apply_V(), applyN(), madness::DFT< T, NDIM >::calculate_tot_pe_sp(), compute_energy(), madness::SCF::do_plots(), MiniDFT::doit(), madness::SCF::initial_guess(), initial_guess(), madness::SCF::initial_guess_from_nwchem(), madness::SCF::initial_load_bal(), madness::SCF::loadbal(), main(), madness::PotentialManager::make_nuclear_potential(), print_info(), madness::SCF::solve(), test_he_potential(), test_hf_be(), test_hf_he(), vnuc(), and madness::PotentialManager::vnuclear().
Variable Documentation
c
double c = 1.86*ctarget static
Referenced by MAKE_PROPAGATOR().
ctarget
double ctarget = 20.0 static
energy_exact
const double energy_exact = -6.188788775728796797594788 static
Referenced by PsiExact::operator()(), and test2().
eshift
const double eshift = 0.0 static
Referenced by PsiExact::operator()(), and Vnuclear::operator()().
G_cache
std::vector< std::pair<double, complex_operatorT*> > G_cache static
Referenced by G().
k
const long k = 12 static
Referenced by MAKE_PROPAGATOR(), and test2().
L
const double L = 100.0 static
Referenced by MAKE_PROPAGATOR(), and test2().
tcrit
double tcrit = 2*constants::pi/(c*c) static
Referenced by test2().
thresh
const double thresh = 1e-8 static
Referenced by test2().
velocity
const double velocity = 3.0 static
Referenced by atom_position(), PsiExact::operator()(), and test2().
vnuc_cache
std::vector< std::pair<double, real_function_1d> > vnuc_cache
Referenced by test2(), and vnuc().
x0
const double x0 = -L + 10.0 static
Referenced by atom_position(), and test2().