MADNESS: test_masks_and_boxes.cc File Reference
test_masks_and_boxes.cc File Reference
#include <madness/chem/masks_and_boxes.h>
#include <madness/mra/mra.h>
Functions
int main (int argc, char **argv)
bool test_smooth_maxout (World &world)
bool test_spherical_box (World &world)
Function Documentation
main()
int main (int argc, char ** argv)
References e(), madness::error(), madness::finalize(), madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), test_smooth_maxout(), test_spherical_box(), and madness::wall_time().
test_smooth_maxout()
bool test_smooth_maxout (World & world)
References madness::max_of_x_1_smooth::compute_factor(), madness::max_of_x_1_smooth::compute_tightness(), madness::filename, madness::nonlinear_vector_solver(), op(), madness::plot_line(), and madness::print().
Referenced by main().
test_spherical_box()
bool test_spherical_box (World & world)
References std::abs(), madness::error(), madness::nonlinear_vector_solver(), offset, madness::print(), madness::Function< T, NDIM >::print_size(), and madness::stringify().
Referenced by main().