MADNESS: test_BSHApply.cc File Reference
test_BSHApply.cc File Reference
#include <madness/mra/mra.h>
#include <madness/chem/BSHApply.h>
#include <madness/world/test_utilities.h>
Classes
struct HO_function< NDIM >
Functions
template<typename T , std::size_t NDIM>
T compute_energy (const Function< double, NDIM > &potential, const Function< T, NDIM > &f)
double compute_energy (const std::vector< int > &n)
template<typename T , std::size_t NDIM>
Tensor< T > compute_fock_matrix (World &world, const Function< double, NDIM > &potential, const std::vector< Function< T, NDIM > > f)
compute the Fock (aka coupling) matrix
int factorial (int n)
double hermite (int n, double x)
int main (int argc, char **argv)
template<std::size_t NDIM>
std::vector< Function< double, NDIM > > mix (const std::vector< Function< double, NDIM > > &vf, const double theta)
template<std::size_t NDIM>
std::vector< Function< double_complex, NDIM > > mix (const std::vector< Function< double_complex, NDIM > > &vf, const double theta)
Tensor< double_complex > su_complex (const double theta)
Tensor< double > su_real (const double theta)
template<typename T , std::size_t NDIM>
int test_converged_function (World &world, double shift, bool coupling)
test the n-dimensional harmonic oscillator
template<typename T , std::size_t NDIM>
int test_convergence (World &world, double shift, bool coupling)
Function Documentation
compute_energy() [1/2]
template<typename T , std::size_t NDIM> T compute_energy (const Function< double, NDIM > & potential, const Function< T, NDIM > & f)
References madness::f, madness::g, madness::grad(), madness::inner(), and potential().
Referenced by test_converged_function().
compute_energy() [2/2]
double compute_energy (const std::vector< int > & n)
References madness::nonlinear_vector_solver().
compute_fock_matrix()
template<typename T , std::size_t NDIM> Tensor< T > compute_fock_matrix (World & world, const Function< double, NDIM > & potential, const std::vector< Function< T, NDIM > > f)
compute the Fock (aka coupling) matrix
References madness::f, madness::grad(), madness::inner(), madness::matrix_inner(), madness::nonlinear_vector_solver(), and potential().
Referenced by test_convergence().
factorial()
int factorial (int n)
References factorial().
Referenced by HO_function< NDIM >::HO_function(), factorial(), and madness::SeparatedConvolution< Q, NDIM >::munorm2_modified().
hermite()
double hermite (int n, double x)
Referenced by HO_function< NDIM >::operator()().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, madness::nonlinear_vector_solver(), madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), shift, madness::startup(), and thresh.
mix() [1/2]
template<std::size_t NDIM> std::vector< Function< double, NDIM > > mix (const std::vector< Function< double, NDIM > > & vf, const double theta)
References MADNESS_ASSERT, madness::nonlinear_vector_solver(), su_real(), and madness::transform().
mix() [2/2]
template<std::size_t NDIM> std::vector< Function< double_complex, NDIM > > mix (const std::vector< Function< double_complex, NDIM > > & vf, const double theta)
References MADNESS_ASSERT, madness::nonlinear_vector_solver(), su_complex(), and madness::transform().
su_complex()
Tensor< double_complex > su_complex (const double theta)
References std::abs(), madness::conj(), madness::inner(), madness::nonlinear_vector_solver(), one(), and madness::print().
Referenced by mix().
su_real()
Tensor< double > su_real (const double theta)
References madness::nonlinear_vector_solver().
Referenced by mix().
test_converged_function()
template<typename T , std::size_t NDIM> int test_converged_function (World & world, double shift, bool coupling)
test the n-dimensional harmonic oscillator
References std::abs(), compute_energy(), e1(), f1, madness::FunctionDefaults< NDIM >::get_thresh(), madness::inner(), k, m, MADNESS_EXCEPTION, mix, NDIM, madness::nonlinear_vector_solver(), madness::Function< T, NDIM >::norm2(), madness::norm2(), potential(), madness::print(), residual(), shift, T(), test(), and thresh.
test_convergence()
template<typename T , std::size_t NDIM> int test_convergence (World & world, double shift, bool coupling)
References compute_fock_matrix(), delta, madness::Tensor< T >::end(), madness::inner(), m, NDIM, madness::nonlinear_vector_solver(), madness::norm2(), madness::normalize(), potential(), residual(), shift, and test().