MADNESS: test_hydro.cc File Reference
test_hydro.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include "dft.h"
Classes
class NuclearChargeDensityOp< T, NDIM >
Macros
#define TO_STRING(s) TO_STRING2(s)
#define TO_STRING2(s) #s
Typedefs
typedef Vector< double, 3 > coordT
Functions
int main (int argc, char **argv)
double psi_func_hydro (const Vector< double, 3 > &r)
static double rho_func_hydro (const coordT &rr)
void test_hydro (World &world)
Variables
const double PI = 3.1415926535897932384
Macro Definition Documentation
TO_STRING
#define TO_STRING (s) TO_STRING2(s)
TO_STRING2
#define TO_STRING2 (s) #s
Typedef Documentation
coordT
typedef Vector<double,3> coordT
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), SafeMPI::Finalize(), madness::BaseTensor::get_instance_count(), madness::World::gop, SafeMPI::Init(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::World::size(), madness::startup(), test_hydro(), and TO_STRING.
psi_func_hydro()
double psi_func_hydro (const Vector< double, 3 > & r)
References madness::nonlinear_vector_solver().
Referenced by test_hydro().
rho_func_hydro()
static double rho_func_hydro (const coordT & rr) static
References c, and madness::nonlinear_vector_solver().
Referenced by test_hydro().
test_hydro()
void test_hydro (World & world)
References e(), SafeMPI::Finalize(), madness::func(), madness::EigSolver< T, NDIM >::get_eig(), madness::EigSolver< T, NDIM >::get_phi(), L, madness::nonlinear_vector_solver(), madness::print(), psi(), psi_func_hydro(), madness::World::rank(), rho_func_hydro(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::EigSolver< T, NDIM >::solve(), thresh, madness::Function< T, NDIM >::thresh(), and madness::Function< T, NDIM >::truncate().
Referenced by main().
Variable Documentation
PI
const double PI = 3.1415926535897932384