MADNESS: test_memory_measurement.cc File Reference
test_memory_measurement.cc File Reference
#include <madness/mra/memory_measurement.h>
#include <madness/world/test_utilities.h>
#include <madness/mra/mra.h>
Functions
static std::shared_ptr< World > create_worlds (World &universe, const std::size_t nsubworld)
int main (int argc, char **argv)
int test_host_rank_map (World &world)
int test_mpi_group (World &world)
int test_node_replicated_function (World &world)
template<std::size_t NDIM>
int test_size (World &world)
Function Documentation
create_worlds()
static std::shared_ptr< World > create_worlds (World & universe, const std::size_t nsubworld) static
for each process create a world using a communicator shared with other processes by round-robin copy-paste from test_world.cc
References madness::WorldMpiInterface::comm(), madness::WorldGopInterface::fence(), madness::World::gop, madness::World::mpi, madness::nonlinear_vector_solver(), madness::World::rank(), and SafeMPI::Intracomm::Split().
Referenced by test_size().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), test_host_rank_map(), test_mpi_group(), test_node_replicated_function(), and thresh.
test_host_rank_map()
int test_host_rank_map (World & world)
test functions to get a map of ranks to hosts and to get the lowest rank on each host
References madness::WorldGopInterface::broadcast_serializable(), madness::test_output::end(), madness::WorldGopInterface::fence(), madness::World::gop, madness::lowest_rank_on_host_of_rank(), madness::nonlinear_vector_solver(), madness::primary_ranks_per_host(), madness::print(), madness::print_header2(), madness::World::rank(), madness::rank_to_host_and_rss_map(), madness::ranks_per_host(), madness::test_output::set_cout_to_terminal(), and madness::World::size().
Referenced by main().
test_mpi_group()
int test_mpi_group (World & world)
test creating 2 distinct MPI groups and communicators then create a world on each communicator and do some work there
print in rank-order
References madness::WorldGopInterface::broadcast_serializable(), madness::test_output::checkpoint(), madness::WorldMpiInterface::comm(), SafeMPI::Intracomm::Create(), madness::test_output::end(), madness::WorldGopInterface::fence(), SafeMPI::Intracomm::Get_group(), madness::get_hostname(), madness::World::gop, h(), SafeMPI::Group::Incl(), madness::lowest_rank_on_host_of_rank(), madness::World::mpi, madness::nonlinear_vector_solver(), madness::primary_ranks_per_host(), madness::print(), madness::World::rank(), madness::ranks_per_host(), madness::test_output::set_cout_to_terminal(), and madness::World::size().
Referenced by main().
test_node_replicated_function()
int test_node_replicated_function (World & world)
replicate a function on all nodes (not ranks) check that all keys are on the expected rank check that the norm of a specific key is the same as in the distributed function
References madness::WorldGopInterface::broadcast_serializable(), madness::test_output::checkpoint(), madness::copy(), madness::test_output::end(), madness::f, f1, madness::WorldGopInterface::fence(), madness::FunctionImpl< T, NDIM >::get_coeffs(), madness::World::gop, madness::lowest_rank_on_host_of_rank(), madness::nonlinear_vector_solver(), madness::Vector< T, N >::normf(), madness::WorldContainer< keyT, valueT, hashfunT >::owner(), madness::primary_ranks_per_host(), madness::print(), madness::World::rank(), madness::rank_to_host_and_rss_map(), madness::ranks_per_host(), madness::test_output::set_cout_to_terminal(), madness::test_output::set_do_print(), madness::World::size(), and madness::Function< T, NDIM >::tree_size().
Referenced by main().
test_size()
template<std::size_t NDIM> int test_size (World & world)
References madness::test_output::checkpoint(), create_worlds(), d, madness::test_output::end(), f2, madness::MemoryMeasurer::measure_and_print(), madness::nonlinear_vector_solver(), madness::print(), madness::print_header2(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_default_pmap(), madness::World::size(), and madness::MemoryMeasurer::total_memory().
Referenced by chunk_example().