MADNESS: test_he.cc File Reference
test_he.cc File Reference
#include <madness/mra/mra.h>
#include <iostream>
#include "solver.h"
#include "poperator.h"
#include "util.h"
#include "xc.h"
Classes
class HeElectronicChargeDensityIGuess< T, NDIM >
class HeNuclearChargeDensityIGuess< T, NDIM >
struct myunaryop_square< T, NDIM >
Macros
#define TO_STRING(s) TO_STRING2(s)
#define TO_STRING2(s) #s
Typedefs
typedef Vector< double, 3 > coordT
Functions
static void he_ldaop (const Key< 3 > &key, Tensor< double > &t)
double he_munge (double r)
int main (int argc, char **argv)
void multiply_op (const Key< 3 > &key, Tensor< double > tcube, Tensor< double > lcube, Tensor< double > rcube)
void printfunc (const World &world, Function< double, 3 > f, int npts)
static double psi_func_he (const coordT &r)
static double rho_func_he (const coordT &rr)
static double smoothed_potential (double r)
Regularized 1/r potential.
static double smoothing_parameter (double Z, double eprec)
Returns radius for smoothing nuclear potential with energy precision eprec.
void test_he_potential (World &world)
void test_hf_he (World &world)
void test_xc (World &world)
static double V_func_he (const coordT &r)
Variables
const double PI = 3.1415926535897932384
Macro Definition Documentation
TO_STRING
#define TO_STRING (s) TO_STRING2(s)
TO_STRING2
#define TO_STRING2 (s) #s
Typedef Documentation
coordT
typedef Vector<double,3> coordT
Function Documentation
he_ldaop()
static void he_ldaop (const Key< 3 > & key, Tensor< double > & t) static
References he_munge(), madness::nonlinear_vector_solver(), q(), and UNARY_OPTIMIZED_ITERATOR.
he_munge()
double he_munge (double r)
References e().
Referenced by he_ldaop().
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::cpu_frequency(), e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::BaseTensor::get_instance_count(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), madness::World::rank(), madness::World::size(), madness::startup(), test_hf_he(), test_xc(), and TO_STRING.
multiply_op()
void multiply_op (const Key< 3 > & key, Tensor< double > tcube, Tensor< double > lcube, Tensor< double > rcube)
References madness::nonlinear_vector_solver(), and TERNARY_OPTIMIZED_ITERATOR.
printfunc()
void printfunc (const World & world, Function< double, 3 > f, int npts)
References madness::f, madness::FunctionDefaults< NDIM >::get_cell_width(), L, madness::nonlinear_vector_solver(), npts, p(), and madness::World::rank().
psi_func_he()
static double psi_func_he (const coordT & r) static
References e(), and madness::nonlinear_vector_solver().
Referenced by test_he_potential().
rho_func_he()
static double rho_func_he (const coordT & rr) static
References c, and madness::nonlinear_vector_solver().
Referenced by test_he_potential().
smoothed_potential()
static double smoothed_potential (double r) static
Regularized 1/r potential.
Invoke as u(r/c)/c where c is the radius of the smoothed volume.
References e(), madness::nonlinear_vector_solver(), PI, and madness::r2().
Referenced by V_func_he().
smoothing_parameter()
static double smoothing_parameter (double Z, double eprec) static
Returns radius for smoothing nuclear potential with energy precision eprec.
References c, e(), eprec, madness::nonlinear_vector_solver(), pow(), and Z.
Referenced by V_func_he().
test_he_potential()
void test_he_potential (World & world)
References madness::apply(), e(), madness::FunctionDefaults< NDIM >::get_cell_width(), madness::inner(), L, madness::nonlinear_vector_solver(), op(), p(), psi(), psi_func_he(), madness::Function< T, NDIM >::reconstruct(), rho_func_he(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::square(), thresh, madness::Function< T, NDIM >::trace(), madness::Function< T, NDIM >::truncate(), V_func_he(), and vnuc().
test_hf_he()
void test_hf_he (World & world)
References e(), L, madness::nonlinear_vector_solver(), p(), madness::ElectronicStructureParams::periodic, psi(), madness::World::rank(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), thresh, madness::Function< T, NDIM >::truncate(), madness::unary_op(), V_func_he(), and vnuc().
Referenced by main().
test_xc()
void test_xc (World & world)
Referenced by main().
V_func_he()
static double V_func_he (const coordT & r) static
References c, e(), madness::nonlinear_vector_solver(), smoothed_potential(), and smoothing_parameter().
Referenced by test_he_potential(), and test_hf_he().
Variable Documentation
PI
const double PI = 3.1415926535897932384
Referenced by smoothed_potential().