MADNESS: testqm.cc File Reference
testqm.cc File Reference
#include <madness/mra/mra.h>
#include <unistd.h>
#include <cstdio>
#include <madness/constants.h>
#include <madness/mra/qmprop.h>
Classes
struct unaryexp< T, NDIM >
Typedefs
typedef Convolution1D< double_complex > complex_operatorT
Functions
complex_function_1d chin_chen (const complex_function_1d &expV, const complex_function_1d &expVtilde, const complex_operatorT *G, const complex_function_1d &psi0)
double_complex dVsq (const coord_1d &r)
double energy (World &world, const complex_function_1d &v, const complex_function_1d &psi)
int main (int argc, char **argv)
complex_function_1d make_exp (double t, const complex_function_1d &v)
Returns exp(-I*t*V) with truncation.
double mask (const coord_1d &r)
double_complex psi0 (const coord_1d &r)
void test_chin_chen (World &world)
void test_trotter (World &world)
complex_function_1d trotter (const complex_function_1d &expV, const complex_operatorT *G, const complex_function_1d &psi0)
double_complex V (const coord_1d &r)
Typedef Documentation
complex_operatorT
typedef Convolution1D<double_complex> complex_operatorT
Function Documentation
chin_chen()
complex_function_1d chin_chen (const complex_function_1d & expV, const complex_function_1d & expVtilde, const complex_operatorT * G, const complex_function_1d & psi0)
References madness::apply_1d_realspace_push(), expV(), madness::nonlinear_vector_solver(), psi0(), madness::Function< T, NDIM >::reconstruct(), and madness::Function< T, NDIM >::truncate().
Referenced by test_chin_chen().
dVsq()
double_complex dVsq (const coord_1d & r)
Referenced by test_chin_chen().
energy()
double energy (World & world, const complex_function_1d & v, const complex_function_1d & psi)
References madness::nonlinear_vector_solver(), madness::print(), psi(), madness::real(), and v.
main()
int main (int argc, char ** argv)
References madness::bandlimited_propagator_plot(), SafeMPI::COMM_WORLD, e(), madness::error(), SafeMPI::Finalize(), SafeMPI::Init_thread(), madness::nonlinear_vector_solver(), madness::print(), and madness::startup().
make_exp()
complex_function_1d make_exp (double t, const complex_function_1d & v)
Returns exp(-I*t*V) with truncation.
References expV(), madness::Function< T, NDIM >::reconstruct(), madness::Function< T, NDIM >::truncate(), madness::Function< T, NDIM >::unaryop(), and v.
mask()
double mask (const coord_1d & r)
psi0()
double_complex psi0 (const coord_1d & r)
References madness::nonlinear_vector_solver().
Referenced by chin_chen(), chin_chen(), chin_chen(), initial_guess(), loadbal(), print_stats(), print_stats(), propagate(), propagate(), propagate(), q_c(), sympgrad4(), sympgrad6(), test2(), test_chin_chen(), test_trotter(), trotter(), trotter(), trotter(), trotter(), and trotter().
test_chin_chen()
void test_chin_chen (World & world)
References madness::abs(), madness::arg(), c, chin_chen(), madness::copy(), dVsq(), e(), energy, expV(), G0, k, L, madness::make_exp(), madness::nonlinear_vector_solver(), madness::phase(), madness::constants::pi, madness::print(), psi(), psi0(), madness::qm_1d_free_particle_propagator(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), tcrit, thresh, tstep, v, and V().
test_trotter()
void test_trotter (World & world)
References madness::abs(), madness::arg(), c, madness::copy(), e(), energy, expV(), G0, k, L, madness::make_exp(), madness::nonlinear_vector_solver(), madness::phase(), madness::constants::pi, madness::print(), psi(), psi0(), madness::qm_1d_free_particle_propagator(), madness::Function< T, NDIM >::scale(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_thresh(), tcrit, thresh, trotter(), tstep, v, and V().
trotter()
complex_function_1d trotter (const complex_function_1d & expV, const complex_operatorT * G, const complex_function_1d & psi0)
References madness::apply_1d_realspace_push(), expV(), madness::nonlinear_vector_solver(), psi0(), and madness::Function< T, NDIM >::reconstruct().
Referenced by test_trotter().
V()
double_complex V (const coord_1d & r)
References m, mask, and madness::nonlinear_vector_solver().
Referenced by test_chin_chen(), and test_trotter().