MADNESS: testgconv.cc File Reference
testgconv.cc File Reference
Test convolution with Gaussian * polyn.
#include <madness/mra/mra.h>
#include <madness/mra/mw.h>
#include <madness/mra/operator.h>
#include <madness/constants.h>
Classes
struct G
struct GConvGNP
struct GConvGRNP
struct GConvGRP
Typedefs
using coord_t = Vector< double, NDIM >
using dim_t = Vector< double, NDIM >
using real_convolution_t = SeparatedConvolution< double, NDIM >
using real_factory_t = FunctionFactory< double, NDIM >
using real_function_t = Function< double, NDIM >
Functions
constexpr dim_t cell_extent ()
Return the size of the simulation cell in user coordinates.
double cell_volume ()
double conv_prime_g (const coord_1d &r)
double convg (const coord_t &r)
double convg1 (const coord_1d &r)
double g (const coord_t &r)
double g1 (const coord_t &r)
double gconvh (const coord_1d &r)
double gd (const coord_t &r)
double gd1 (const coord_t &r)
double gprime (const coord_1d &r)
double gt (const coord_t &r)
double gt1 (const coord_t &r)
double h (const coord_1d &r)
int main (int argc, char **argv)
constexpr coord_t one (1.0)
constexpr double rhunit (const coord_t &r)
constexpr double s_13_4177_0 (const coord_t &r)
int test_gconv (World &world)
double unit (const coord_t &r)
Variables
static const int k = 10
static constexpr double L = 50
static constexpr double Lx = L
static constexpr double Ly = L
static constexpr double Lz = L
constexpr auto make_rx
constexpr std::size_t NDIM = 1
const auto npts = 10001
constexpr coord_t onex = make_rx(1.)
static const double thresh = 1e-6
Detailed Description
Test convolution with Gaussian * polyn.
Typedef Documentation
coord_t
using coord_t = Vector<double,NDIM>
dim_t
using dim_t = Vector<double,NDIM>
real_convolution_t
using real_convolution_t = SeparatedConvolution<double, NDIM>
real_factory_t
using real_factory_t = FunctionFactory<double, NDIM>
real_function_t
using real_function_t = Function<double, NDIM>
Function Documentation
cell_extent()
constexpr dim_t cell_extent () constexpr
Return the size of the simulation cell in user coordinates.
References Lx, Ly, and NDIM.
Referenced by cell_volume(), gd(), and gd1().
cell_volume()
double cell_volume ()
References cell_extent(), madness::nonlinear_vector_solver(), and v.
Referenced by madness::FunctionImpl< T, NDIM >::eval_cube(), gd(), gd1(), rhunit(), and unit().
conv_prime_g()
double conv_prime_g (const coord_1d & r)
References madness::nonlinear_vector_solver(), and madness::constants::pi.
Referenced by test_gconv().
convg()
double convg (const coord_t & r)
References madness::inner(), NDIM, madness::nonlinear_vector_solver(), madness::constants::pi, and pow().
Referenced by test_gconv().
convg1()
double convg1 (const coord_1d & r)
References madness::nonlinear_vector_solver(), and madness::constants::pi.
Referenced by test_gconv().
g()
double g (const coord_t & r)
References madness::inner(), madness::constants::inv_sqrt_pi, madness::nonlinear_vector_solver(), and madness::Vector< double, NDIM >::static_size.
Referenced by fit(), main(), makedata(), operator<<(), AtomicBasisSet::read_file(), and updatex().
g1()
double g1 (const coord_t & r)
References madness::inner(), madness::constants::inv_sqrt_pi, madness::nonlinear_vector_solver(), onex, and madness::Vector< double, NDIM >::static_size.
Referenced by madness::FunctionCommonData< T, NDIM >::_init_twoscale(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::activate(), madness::FunctionImpl< T, NDIM >::add_op::activate(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::activate(), madness::FunctionImpl< T, NDIM >::project_out_op< LDIM >::activate(), madness::Solver< T, NDIM >::apply_hf_exchange(), madness::FunctionImpl< T, NDIM >::add_op::forward_ctor(), madness::FunctionImpl< T, NDIM >::multiply_op< LDIM >::forward_ctor(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::forward_ctor(), data< T, NDIM >::initialize(), madness::load_coeffs(), plotter1(), madness::read_twoscale(), test(), test_gconv(), test_in(), test_out(), test_partial_inner(), test_projector(), test_projector_outer(), test_Q12_projector(), madness::two_scale_coefficients(), and madness::two_scale_hg().
gconvh()
double gconvh (const coord_1d & r)
References madness::nonlinear_vector_solver().
Referenced by test_gconv().
gd()
double gd (const coord_t & r)
References cell_extent(), cell_volume(), madness::inner(), madness::constants::inv_sqrt_pi, madness::nonlinear_vector_solver(), and madness::Vector< double, NDIM >::static_size.
gd1()
double gd1 (const coord_t & r)
References cell_extent(), cell_volume(), madness::inner(), madness::constants::inv_sqrt_pi, madness::nonlinear_vector_solver(), onex, and madness::Vector< double, NDIM >::static_size.
gprime()
double gprime (const coord_1d & r)
References madness::nonlinear_vector_solver(), and madness::constants::pi.
Referenced by test_gconv().
gt()
double gt (const coord_t & r)
References alpha, madness::inner(), madness::constants::inv_sqrt_pi, madness::nonlinear_vector_solver(), and madness::Vector< double, NDIM >::static_size.
Referenced by madness::PNOParameters::set_derived_values().
gt1()
double gt1 (const coord_t & r)
References alpha, madness::inner(), madness::constants::inv_sqrt_pi, madness::nonlinear_vector_solver(), onex, and madness::Vector< double, NDIM >::static_size.
h()
double h (const coord_1d & r)
References madness::nonlinear_vector_solver().
Referenced by madness::ConcurrentHashMap< keyT, valueT, hashfunT >::ConcurrentHashMap(), a_fit(), apbar_fit(), arithmetic_series(), madness::GFit< T, NDIM >::bsh_fit(), madness::GFit< T, NDIM >::bsh_fit_ndim(), bshrel_fit(), madness::FunctionImpl< Q, NDIM >::check_symmetry_local(), madness::FunctionImpl< T, NDIM >::do_print_grid(), madness::FunctionImpl< T, NDIM >::downsample(), madness::FunctionImpl< Q, NDIM >::evalR(), madness::fcube(), fit(), gen_ce(), madness::MP2::guess_mp1_3(), madness::Atom::hash(), madness::Molecule::hash(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), linspace(), main(), main(), DF::make_component_lineplots(), DF::make_component_logplots(), DF::make_density_lineplots(), madness::Nemo::make_incomplete_hessian_response_part(), make_pts(), munge_quadrature_points(), BoysLocalization::operator()(), madness::ConcurrentHashMap< keyT, valueT, hashfunT >::operator=(), madness::FunctionImpl< T, NDIM >::partial_inner(), madness::FunctionImpl< T, NDIM >::partial_inner_contract(), madness::SeparatedConvolution< Q, NDIM >::partial_upsample(), pbar_fit(), plot(), madness::FunctionImpl< T, NDIM >::plot_cube_kernel(), madness::plot_line(), madness::plot_line(), madness::plot_line(), madness::plot_line(), madness::plot_line(), madness::plot_line(), Calculation::plot_p(), madness::plotdx(), madness::RMI::RmiTask::process_some(), madness::LowRankFunctionFactory< T, NDIM, LDIM >::project(), madness::FunctionImpl< T, NDIM >::read_grid(), madness::FunctionImpl< T, NDIM >::read_grid2(), madness::GaussianConvolution1D< Q >::rnlp(), madness::GFit< T, NDIM >::slater_fit(), madness::Nemo::solve_cphf(), tbar_fit(), test(), test_gconv(), test_mpi_group(), test_plot(), updatex(), madness::SeparatedConvolution< Q, NDIM >::upsample(), and madness::FunctionImpl< T, NDIM >::upsample().
main()
int main (int argc, char ** argv)
References e(), madness::error(), madness::finalize(), madness::initialize(), k, L, madness::nonlinear_vector_solver(), madness::print(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), test_gconv(), and thresh.
one()
constexpr coord_t one (1. 0) constexpr
Referenced by apply_potential(), bshrel_omega(), cfrac(), madness::OEP::compute_slater_potential(), jacobi(), kinetic_energy_matrix(), kinetic_energy_matrix2(), Ansatz0::make_guess(), makedata(), madness::mTxm(), mTxm_dgemm(), mTxm_zgemm(), madness::mTxmq(), madness::mTxmT(), madness::mxm(), madness::mxmT(), madness::LRFunctorF12< T, NDIM, LDIM >::norm2(), opt(), opt(), Ansatz0::R(), slymer::NWChem_Interface::read_movecs(), Ansatz0::Rinv(), su_complex(), test(), test_construction_optimization(), test_Kcommutator(), test_lowrank_function(), test_molecular_grid(), test_orthogonalization(), test_swap_particles(), madness::SubspaceK< T, NDIM >::update_subspace(), madness::Subspace< T, NDIM >::update_subspace(), Subspace::update_subspace(), Subspace::update_subspace(), and updatex().
rhunit()
constexpr double rhunit (const coord_t & r) constexpr
References cell_volume().
s_13_4177_0()
constexpr double s_13_4177_0 (const coord_t & r) constexpr
References L, madness::nonlinear_vector_solver(), and pow().
test_gconv()
int test_gconv (World & world)
References madness::abs(), madness::BC_PERIODIC, check(), conv_prime_g(), convg(), convg1(), madness::copy(), d, madness::displacement(), e(), madness::error(), exact, madness::f, f1, madness::WorldGopInterface::fence(), madness::g, g1(), gconvh(), madness::FunctionDefaults< NDIM >::get_thresh(), madness::World::gop, gprime(), h(), k, L, lo, MADNESS_ASSERT, make_rx, NDIM, madness::nonlinear_vector_solver(), madness::norm2(), npts, op(), madness::constants::pi, madness::plot_line(), madness::print(), q(), R, madness::World::rank(), madness::FunctionDefaults< NDIM >::set_bc(), sigma, thresh, madness::to_string(), madness::Function< T, NDIM >::trace(), madness::Function< T, NDIM >::truncate(), V(), and V2.
Referenced by main().
unit()
double unit (const coord_t & r)
References cell_volume().
Referenced by CheckUnit(), madness::cstr_to_memory_size(), getwa_(), main(), madness::smooth< T, NDIM >::make_inv_mask(), madness::PNO::orthonormalize_cholesky(), PrintFileStats(), putwa_(), wclose_(), and wopen_().
Variable Documentation
k
const int k = 10 static
Referenced by main(), and test_gconv().
L
constexpr double L = 50 static constexpr
Referenced by main(), s_13_4177_0(), and test_gconv().
Lx
constexpr double Lx = L static constexpr
Referenced by cell_extent().
Ly
constexpr double Ly = L static constexpr
Referenced by cell_extent().
Lz
constexpr double Lz = L static constexpr
make_rx
constexpr auto make_rx constexpr
Initial value:
= [](double x) -> coord_t {
  static_assert(NDIM >= 1 && NDIM <= 3);
  if constexpr (NDIM==1)
    return {x};
  else if constexpr (NDIM==2)
    return {x, 0.0};
  else
    return {x, 0.0, 0.0};
}
Referenced by test_gconv().
NDIM
constexpr std::size_t NDIM = 1 constexpr
Referenced by madness::BoundaryConditions< NDIM >::BoundaryConditions(), madness::BoundaryConditions< NDIM >::BoundaryConditions(), madness::BoundaryConditions< NDIM >::BoundaryConditions(), madness::BoxSurfaceDisplacementValidator< NDIM >::BoxSurfaceDisplacementValidator(), madness::cartesian_grid< NDIM >::cartesian_grid(), madness::Derivative< T, NDIM >::Derivative(), madness::dftgrid< NDIM >::dftgrid(), madness::Displacements< NDIM >::Displacements(), madness::FunctionCommonData< T, NDIM >::FunctionCommonData(), FunctionIOData< T, NDIM >::FunctionIOData(), GaussianGuess< NDIM >::GaussianGuess(), madness::FunctionImpl< T, NDIM >::hartree_op< LDIM, leaf_opT >::hartree_op(), HO_function< NDIM >::HO_function(), madness::BoxSurfaceDisplacementRange< NDIM >::Iterator::Iterator(), madness::MemoryMeasurer::MemKey::MemKey(), madness::molecular_grid< NDIM >::molecular_grid(), madness::NuclearCuspyBox_op< T, NDIM >::NuclearCuspyBox_op(), madness::NuclearCuspyBox_op< T, NDIM >::NuclearCuspyBox_op(), ParserHandler< T, NDIM >::ParserHandler(), madness::FunctionImpl< T, NDIM >::recursive_apply_op< opT, LDIM >::recursive_apply_op(), madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::ScalingFunctionFunctor(), madness::TwoElectronFactory< T, NDIM >::TwoElectronFactory(), madness::TwoElectronInterface< T, NDIM >::TwoElectronInterface(), madness::add(), madness::add(), madness::add(), madness::add(), madness::MemoryMeasurer::add_memory_to_map(), madness::FunctionImpl< T, NDIM >::add_scalar_inplace(), madness::BoxSurfaceDisplacementRange< NDIM >::Iterator::advance(), madness::SeparatedConvolution< Q, NDIM >::apply(), madness::AC< NDIM >::apply(), madness::apply(), madness::apply(), madness::apply(), madness::apply(), madness::SeparatedConvolution< Q, NDIM >::apply2(), madness::SeparatedConvolution< Q, NDIM >::apply2_lowdim(), madness::apply_1d_realspace_push(), madness::apply_only(), madness::SeparatedConvolution< Q, NDIM >::apply_transformation(), madness::SeparatedConvolution< Q, NDIM >::apply_transformation2(), bench_cell(), madness::binary_op(), bind_function_type(), madness::Displacements< NDIM >::bmax_default(), madness::Specialbox_op< T, NDIM >::box_is_at_boundary(), madness::Key< NDIM >::break_apart(), madness::FunctionImpl< T, NDIM >::broaden(), madness::GFit< T, NDIM >::BSHFit(), cell_extent(), madness::SeparatedConvolution< Q, NDIM >::check_cubic(), madness::FunctionImpl< T, NDIM >::child_patch(), madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::FunctionCommonFunctionality< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::FunctionImpl< T, NDIM >::coeffs2values(), madness::SeparatedConvolution< Q, NDIM >::combine(), madness::NemoBase::compute_kinetic_energy(), madness::NemoBase::compute_kinetic_energy1a(), convg(), FunctionIOData< T, NDIM >::create_function(), madness::projector_irrep::create_symmetry_adapted_basis(), madness::cross(), diff(), madness::Function< T, NDIM >::dirac_convolution(), madness::Key< NDIM >::distsq(), madness::Key< NDIM >::distsq_bc(), madness::Key< NDIM >::distsq_bc(), madness::div(), madness::FunctionImpl< T, NDIM >::do_apply(), madness::FunctionImpl< T, NDIM >::do_apply_directed_screening(), madness::FunctionImpl< T, NDIM >::do_apply_kernel3(), madness::FunctionImpl< T, NDIM >::do_binary_op(), madness::DerivativeBase< T, NDIM >::do_diff1(), madness::Derivative< T, NDIM >::do_diff2b(), madness::FunctionImpl< T, NDIM >::do_mul(), madness::FunctionImpl< T, NDIM >::do_print_grid(), madness::FunctionImpl< T, NDIM >::do_print_tree_graphviz(), Plotter::dolineplot(), Plotter::dolineplot(), Plotter::dovolumeplot(), Plotter::dovolumeplot(), madness::FunctionImpl< T, NDIM >::downsample(), madness::FunctionImpl< T, NDIM >::err_box(), madness::SeparatedConvolution< Q, NDIM >::estimate_costs(), madness::Function< T, NDIM >::eval(), madness::FunctionImpl< T, NDIM >::eval(), madness::Function< T, NDIM >::eval_cube(), madness::FunctionImpl< T, NDIM >::eval_cube(), madness::Function< T, NDIM >::eval_local_only(), madness::FunctionImpl< T, NDIM >::eval_local_only(), madness::Function< T, NDIM >::eval_local_only(), madness::FunctionImpl< T, NDIM >::eval_local_only(), madness::FunctionImpl< T, NDIM >::eval_plot_cube(), PyFunctor< T, NDIM >::eval_scalar_loop(), PyFunctor< T, NDIM >::eval_vectorized(), madness::Function< T, NDIM >::evaldepthpt(), madness::FunctionImpl< T, NDIM >::evaldepthpt(), madness::Function< T, NDIM >::evalR(), madness::FunctionImpl< T, NDIM >::evalR(), madness::Key< NDIM >::extract_back(), madness::Key< NDIM >::extract_complement_key(), madness::Key< NDIM >::extract_front(), madness::fcube(), madness::fcube(), madness::fcube(), madness::FunctionImpl< T, NDIM >::fcube_for_mul(), madness::FunctionImpl< T, NDIM >::fcube_for_mul(), filter_moments_inplace(), gaussian_func(), madness::randomgrid< NDIM >::gaussian_random_distribution(), madness::gaxpy(), madness::VectorSpace< T, NDIM >::gaxpy(), madness::gaxpy_oop(), madness::FunctionDefaults< NDIM >::get_bc(), madness::cartesian_grid< NDIM >::get_coordinates(), madness::Displacements< NDIM >::get_disp(), xc_functor< NDIM >::get_distance(), madness::atom_information< NDIM >::get_distance(), madness::int_factor_functor< NDIM >::get_distance(), madness::lr_pot_functor< NDIM >::get_distance(), madness::randomgrid< NDIM >::get_grid(), madness::molecular_grid< NDIM >::get_grid(), madness::SeparatedConvolution< Q, NDIM >::get_source_key(), madness::SeparatedConvolution< Q, NDIM >::getmuop(), madness::SeparatedConvolution< Q, NDIM >::getmuop_modified(), madness::SeparatedConvolution< Q, NDIM >::getop_modified(), golden_check_ndim(), madness::grad(), madness::grad_ble_one(), madness::grad_ble_two(), madness::grad_bpsline_two(), madness::grad_bspline_one(), madness::grad_bspline_three(), madness::gradient_operator(), madness::imag(), madness::LBNodeDeux< NDIM >::index(), madness::SeparatedConvolution< Q, NDIM >::init_lattice_summed(), madness::SeparatedConvolution< Q, NDIM >::init_range(), data< T, NDIM >::initialize(), madness::cartesian_grid< NDIM >::initialize(), FunctionIOData< T, NDIM >::initialize_func_coeffs(), madness::inner(), madness::inner(), madness::inner(), madness::VectorSpace< T, NDIM >::inner(), madness::FunctionImpl< T, NDIM >::inner_ext_recursive(), madness::innerXX(), madness::Key< NDIM >::is_farther_out_than(), madness::Key< NDIM >::is_neighbor_of(), madness::Key< NDIM >::is_neighbor_of(), kinetic_energy_matrix(), madness::Kinetic< T, NDIM >::kinetic_energy_matrix(), madness::Kinetic< T, NDIM >::kinetic_energy_matrix(), kinetic_energy_matrix2(), kinetic_energy_matrix_slow(), laplacian(), madness::ConvolutionND< Q, NDIM >::lattice_summed(), madness::Function< T, NDIM >::load(), main(), madness::TwoElectronInterface< T, NDIM >::make_coeff(), madness::SeparatedConvolution< Q, NDIM >::make_coeff_for_operator(), madness::FunctionDefaults< NDIM >::make_default_cell(), madness::FunctionDefaults< NDIM >::make_default_cell_width(), madness::Displacements< NDIM >::make_disp(), madness::Displacements< NDIM >::make_disp_periodic(), madness::smooth< T, NDIM >::make_sigma(), madness::SeparatedConvolution< Q, NDIM >::make_tt_representation(), madness::FunctionImpl< T, NDIM >::make_Vphi(), madness::Function< T, NDIM >::map_and_mirror(), madness::TwoElectronInterface< T, NDIM >::map_coeff(), madness::Function< T, NDIM >::mapdim(), madness::EigSolver< T, NDIM >::matrix_element(), madness::smooth< T, NDIM >::merge_functions(), madness::Key< NDIM >::merge_with(), madness::Function< T, NDIM >::mirror(), madness::mul(), madness::FunctionImpl< T, NDIM >::mul(), madness::mul(), madness::mul(), madness::mul_sparse(), madness::FunctionImpl< T, NDIM >::multiply(), madness::multiply(), madness::SeparatedConvolution< Q, NDIM >::munorm2_modified(), madness::SeparatedConvolution< Q, NDIM >::munorm2_ns(), madness::SeparatedConvolution< Q, NDIM >::muopxv_fast(), madness::SeparatedConvolution< Q, NDIM >::muopxv_fast2(), madness::FunctionImpl< T, NDIM >::neighbor(), madness::FunctionImpl< T, NDIM >::neighbor_in_volume(), madness::VectorSpace< T, NDIM >::norm(), madness::FunctionImpl< T, NDIM >::norm_tree_spawn(), madness::FunctionImpl< T, NDIM >::NS_fcube_for_mul(), madness::FunctionImpl< T, NDIM >::NScoeffs2values(), madness::CCConvolutionOperator< T, NDIM >::operator()(), HeElectronicChargeDensityIGuess< T, NDIM >::operator()(), HeNuclearChargeDensityIGuess< T, NDIM >::operator()(), ParserHandler< T, NDIM >::operator()(), madness::ComplexExp< NDIM >::operator()(), Gaussian< T, NDIM >::operator()(), DerivativeGaussian< T, NDIM >::operator()(), GaussianGuess< NDIM >::operator()(), madness::pg_operator::operator()(), madness::FunctionImpl< T, NDIM >::Vphi_op_NS< opT, LDIM >::operator()(), madness::ElectronCuspyBox_op< T, NDIM >::operator()(), madness::NuclearCuspyBox_op< T, NDIM >::operator()(), madness::hartree_leaf_op< T, NDIM >::operator()(), madness::BoxSurfaceDisplacementValidator< NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), madness::DNuclear< T, NDIM >::operator()(), madness::projector_irrep::operator()(), madness::projector_irrep::operator()(), gauss< T, NDIM >::operator()(), HO_function< NDIM >::operator()(), madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::operator()(), Oscillatory< NDIM >::operator()(), madness::Function< T, NDIM >::operator()(), madness::FunctionImpl< T, NDIM >::do_inner_local_on_demand< R >::operator()(), madness::FunctionImpl< T, NDIM >::do_check_symmetry_local::operator()(), madness::FunctionImpl< T, NDIM >::do_mapdim::operator()(), madness::FunctionImpl< T, NDIM >::do_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_map_and_mirror::operator()(), madness::FunctionImpl< T, NDIM >::do_unary_op_value_inplace< opT >::operator()(), madness::operator*(), madness::LowRankFunction< T, NDIM, LDIM >::operator*(), madness::operator*(), madness::operator*(), madness::operator*(), madness::KeyChildIterator< NDIM >::operator++(), madness::operator-(), madness::Function< T, NDIM >::operator-=(), madness::Key< NDIM >::operator<(), madness::operator<<(), madness::BoundaryConditions< NDIM >::operator=(), madness::Key< NDIM >::operator==(), madness::PlotParameters::origin(), madness::Key< NDIM >::parent(), madness::FunctionImpl< T, NDIM >::parent_to_child(), madness::SeparatedConvolution< Q, NDIM >::partial_upsample(), madness::PeriodicBSHOp(), madness::PeriodicBSHOpPtr(), madness::PeriodicCoulombOp(), madness::PeriodicCoulombOpPtr(), madness::FunctionImpl< Q, NDIM >::plot_cube_kernel(), madness::FunctionImpl< T, NDIM >::plot_cube_kernel(), madness::plot_line(), madness::plot_line(), madness::plot_line(), madness::plot_line(), madness::plot_line(), madness::plot_line(), madness::plot_plane(), madness::plot_plane(), madness::plot_plane(), madness::plotdx(), plotvtk(), madness::plotvtk_begin(), madness::plotvtk_data(), madness::plotvtk_data(), madness::plotvtk_end(), madness::FunctionDefaults< NDIM >::print(), madness::FunctionImpl< T, NDIM >::print_stats(), madness::print_tree_jsonfile(), madness::Function< T, NDIM >::project_out(), random_sim_points(), RandomGaussian(), madness::OperatorInfo::range_as_array(), FunctionIO< T, NDIM >::read_function(), read_function(), read_function_coeffs(), FunctionIO< T, NDIM >::read_function_coeffs(), read_function_coeffs(), madness::FunctionImpl< T, NDIM >::read_grid(), madness::FunctionImpl< T, NDIM >::read_grid2(), madness::real(), madness::Key< NDIM >::real_distsq(), madness::Key< NDIM >::real_distsq_bc(), madness::FunctionDefaults< NDIM >::recompute_cell_info(), madness::rot(), run_batched_cell(), FunctionIOData< T, NDIM >::set_function_coeffs(), madness::SCF::set_protocol(), sim_to_user(), madness::sim_to_user(), simpt2key(), madness::simpt2key(), madness::smooth< T, NDIM >::smooth_sigma(), madness::SmoothingOperator(), madness::ScalingFunctionFunctor< NDIM, std::enable_if_t< std::greater{}(NDIM, 1)> >::special_points(), madness::Function< T, NDIM >::store(), madness::sub(), madness::sub(), madness::swap_particles(), madness::symmetrize(), madness::guessfactory::tensor_to_coord(), test_add(), test_apply(), test_apply_push_1d(), test_arithmetic(), test_asymmetric(), test_basic(), test_batched_ndim(), test_consolidate(), test_consolidate_vs_direct(), test_construction_optimization(), test_constructor(), test_conv(), test_converged_function(), test_convergence(), test_correctness_ndim(), test_cross(), test_diff(), test_dot(), test_full_rank_functor(), test_gconv(), test_hartree_product(), test_inner(), test_inner(), test_inner(), test_io(), test_Kcommutator(), test_kinetic(), test_load_store(), test_lowrank_function(), test_math(), test_matrix_mul_sparse(), test_molecular_grid(), test_multi_to_multi_op(), test_multiply(), test_multiply(), test_multiply_with_f12(), test_norm(), test_op(), test_operator_apply(), test_orthonormalize_canonical(), test_orthonormalize_symmetric(), test_output_param_overload(), test_partial_inner_3d(), test_partial_inner_6d(), test_plot(), test_proj(), test_projector(), test_projector(), test_projector_outer(), test_Q12_projector(), test_rot(), test_scalar_multiplication(), test_swap_particles(), test_transform(), test_transformations(), test_tt2d_summation(), test_unaryop(), test_vector_composite(), test_with_function_vector(), madness::Key< NDIM >::thisKeyContains(), madness::FunctionImpl< T, NDIM >::trace_local(), madness::transform(), madness::transform(), madness::truncate(), madness::FunctionImpl< T, NDIM >::truncate_op(), madness::FunctionImpl< T, NDIM >::truncate_reconstructed_spawn(), madness::FunctionImpl< T, NDIM >::truncate_spawn(), madness::FunctionImpl< T, NDIM >::truncate_tol(), madness::CCConvolutionOperator< T, NDIM >::update_elements(), madness::FunctionImpl< T, NDIM >::upsample(), madness::user_to_sim(), GaussianGuess< NDIM >::val(), madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs(), madness::FunctionCommonFunctionality< T, NDIM >::values2coeffs(), madness::FunctionImpl< T, NDIM >::values2coeffs(), madness::FunctionImpl< T, NDIM >::values2coeffs(), madness::FunctionImpl< T, NDIM >::values2NScoeffs(), madness::gridbase::visualize(), madness::randomgrid< NDIM >::volume(), madness::cartesian_grid< NDIM >::volume_per_gridpoint(), FunctionIO< T, NDIM >::write_function(), write_function(), write_function_coeffs(), and FunctionIO< T, NDIM >::write_function_coeffs().
npts
const auto npts = 10001
Referenced by PyFunctor< T, NDIM >::eval_scalar_loop(), PyFunctor< T, NDIM >::eval_vectorized(), main(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), PyFunctor< T, NDIM >::operator()(), madness::ProjRLMFunctor::operator()(), print_cube(), print_cube(), print_cube(), printfunc(), madness::Gnuplot::test(), test(), test_gconv(), test_gence(), test_gence2(), test_nuclear_potential(), test_nuclear_potential2(), test_nuclear_potential3(), test_nuclear_potential_big_unit_cell(), madness::Solver< T, NDIM >::test_periodicity(), and testNavierStokes().
onex
constexpr coord_t onex = make_rx(1.) constexpr
Referenced by g1(), gd1(), and gt1().
thresh
const double thresh = 1e-6 static
Referenced by main(), and test_gconv().