MADNESS: testsolver.cc File Reference
testsolver.cc File Reference
#include <iostream>
#include <madness/mra/nonlinsol.h>
#include <cmath>
#include <madness/world/test_utilities.h>
Classes
struct F
simple class for testing the solver
struct function_allocator< T, NDIM >
Functions
F allocator ()
template<typename T , std::size_t NDIM>
Function< T, NDIM > compute_update (World &world, const Function< T, NDIM > &f)
F exact_solution ()
double inner (const F &a, const F &b)
int main (int argc, char **argv)
F residual (const F &f)
int test_simple (World &world)
template<typename T , std::size_t NDIM>
int test_with_function (World &world)
template<typename T , std::size_t NDIM>
int test_with_function_vector (World &world)
test solver with a vector of functions
Function Documentation
allocator()
F allocator ()
compute_update()
template<typename T , std::size_t NDIM> Function< T, NDIM > compute_update (World & world, const Function< T, NDIM > & f)
References madness::f, madness::inner(), madness::nonlinear_vector_solver(), op(), and V().
Referenced by test_with_function(), and test_with_function_vector().
exact_solution()
F exact_solution ()
Referenced by test_simple().
inner()
double inner (const F & a, const F & b)
References a, and b.
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_tensor_type(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::startup(), test_simple(), and madness::TT_2D.
residual()
F residual (const F & f)
References madness::f, and F::get().
Referenced by test_simple(), test_with_function(), and test_with_function_vector().
test_simple()
int test_simple (World & world)
References madness::test_output::checkpoint(), madness::cpu_time(), madness::test_output::end(), madness::error(), exact_solution(), F::get(), madness::nonlinear_vector_solver(), and residual().
Referenced by main(), and simple_example().
test_with_function()
template<typename T , std::size_t NDIM> int test_with_function (World & world)
References madness::test_output::checkpoint(), compute_update(), madness::copy(), madness::cpu_time(), madness::test_output::end(), madness::f, guess(), madness::XNonlinearSolver< T, C, Alloc >::initialize(), madness::inner(), madness::nonlinear_vector_solver(), madness::Function< T, NDIM >::norm2(), madness::norm2(), madness::print(), residual(), and madness::XNonlinearSolver< T, C, Alloc >::update().
test_with_function_vector()
template<typename T , std::size_t NDIM> int test_with_function_vector (World & world)
test solver with a vector of functions
keep it simple: both functions converge to the same state, no orthogonalization needed
References madness::test_output::checkpoint(), compute_update(), madness::copy(), madness::cpu_time(), madness::test_output::end(), madness::f, f1, f2, guess(), madness::inner(), NDIM, madness::nonlinear_vector_solver(), madness::norm2(), madness::normalize(), madness::print(), madness::reconstruct(), residual(), and madness::test_output::set_cout_to_terminal().