MADNESS: test_eval.cc File Reference
test_eval.cc File Reference
Targeted unit tests for FunctionImpl::eval_local_only and eval_cube.
#include <madness/mra/mra.h>
#include <madness/mra/funcdefaults.h>
#include <madness/world/test_utilities.h>
#include <madness/tensor/tensor.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <limits>
#include <random>
#include <string>
#include <vector>
Classes
class Constant< T, NDIM >
class Gaussian< T, NDIM >
struct GoldenPoint
class Oscillatory< NDIM >
Functions
template<std::size_t NDIM>
void bench_cell (World &world, int k)
static double eval_tol (double ref, double k_factor=1.0)
template<std::size_t NDIM>
bool golden_check_ndim (World &world, int k, double thresh, double cx, const double raw_pt[3], double &out_ref, double &out_lo)
static bool is_heavy (std::size_t ndim, int k, double thresh)
int main (int argc, char **argv)
template<std::size_t NDIM>
std::vector< Vector< double, NDIM > > random_sim_points (int n, uint64_t seed)
template<std::size_t NDIM>
int run_batched_cell (World &world, const std::string &label, int k, double thresh, double L, const std::vector< Vector< double, NDIM > > &user_pts)
void run_benchmark (World &world)
template<typename FunctorT , std::size_t NDIM>
int run_correctness_cell (World &world, const std::string &label, FunctorT *raw_functor, int k, double thresh, double L, const std::vector< Vector< double, NDIM > > &user_pts)
template<std::size_t NDIM>
Vector< double, NDIM > sim_to_user (const Vector< double, NDIM > &xsim, const Tensor< double > &cell)
template<std::size_t NDIM>
int test_batched_ndim (World &world)
int test_contraction_micro ()
template<std::size_t NDIM>
int test_correctness_ndim (World &world)
int test_general_fast_transform ()
int test_golden_values (World &world)
int test_output_param_overload (World &world)
int test_scaling_factor ()
Variables
static const GoldenPoint golden_pts []
static const bool print_golden
static const bool run_bench
static const bool run_heavy
Detailed Description
Targeted unit tests for FunctionImpl::eval_local_only and eval_cube.
Covers:
correctness matrix: NDIM x k x thresh x functor x point location x ranks
golden-value characterization: pins computed values to guard silent drift
micro-test #1: contraction correctness (raw loop vs separated form)
micro-test #2: scaling factor (exp2 vs pow, cached 1/sqrt(V))
Heavy cells (NDIM==6, k>8, thresh<=1e-8) are compiled but skipped at runtime unless MADNESS_TEST_EVAL_EXHAUSTIVE=1 is set.
Function Documentation
bench_cell()
template<std::size_t NDIM> void bench_cell (World & world, int k)
References c, d, e(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, NDIM, madness::nonlinear_vector_solver(), madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), and madness::Vector< T, N >::size().
eval_tol()
static double eval_tol (double ref, double k_factor = 1.0) static
References std::abs(), e(), and madness::nonlinear_vector_solver().
Referenced by run_correctness_cell().
golden_check_ndim()
template<std::size_t NDIM> bool golden_check_ndim (World & world, int k, double thresh, double cx, const double raw_pt[3], double & out_ref, double & out_lo)
References d, madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, lo, NDIM, madness::nonlinear_vector_solver(), print_golden, madness::World::rank(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), and thresh.
is_heavy()
static bool is_heavy (std::size_t ndim, int k, double thresh) static
References e(), k, and thresh.
Referenced by test_correctness_ndim().
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), run_bench, run_benchmark(), run_heavy, madness::startup(), test_contraction_micro(), test_general_fast_transform(), test_golden_values(), test_output_param_overload(), and test_scaling_factor().
random_sim_points()
template<std::size_t NDIM> std::vector< Vector< double, NDIM > > random_sim_points (int n, uint64_t seed)
References d, dist(), NDIM, madness::nonlinear_vector_solver(), and p().
run_batched_cell()
template<std::size_t NDIM> int run_batched_cell (World & world, const std::string & label, int k, double thresh, double L, const std::vector< Vector< double, NDIM > > & user_pts)
References madness::test_output::checkpoint(), d, madness::test_output::end(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, NDIM, madness::nonlinear_vector_solver(), ok(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::WorldGopInterface::sum(), and thresh.
run_benchmark()
void run_benchmark (World & world)
References madness::nonlinear_vector_solver(), madness::World::rank(), and madness::World::size().
Referenced by main().
run_correctness_cell()
template<typename FunctorT , std::size_t NDIM> int run_correctness_cell (World & world, const std::string & label, FunctorT * raw_functor, int k, double thresh, double L, const std::vector< Vector< double, NDIM > > & user_pts)
References std::abs(), madness::test_output::checkpoint(), madness::test_output::end(), eval_tol(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, L, lo, madness::nonlinear_vector_solver(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::WorldGopInterface::sum(), and thresh.
sim_to_user()
template<std::size_t NDIM> Vector< double, NDIM > sim_to_user (const Vector< double, NDIM > & xsim, const Tensor< double > & cell)
References d, NDIM, and madness::nonlinear_vector_solver().
test_batched_ndim()
template<std::size_t NDIM> int test_batched_ndim (World & world)
References c, d, e(), k, L, NDIM, madness::nonlinear_vector_solver(), p(), and thresh.
test_contraction_micro()
int test_contraction_micro ()
References std::abs(), c, madness::test_output::checkpoint(), d, dist(), e(), madness::test_output::end(), k, madness::MAXK, madness::nonlinear_vector_solver(), p(), and q().
Referenced by main().
test_correctness_ndim()
template<std::size_t NDIM> int test_correctness_ndim (World & world)
References c, d, e(), is_heavy(), k, L, NDIM, madness::nonlinear_vector_solver(), p(), q(), run_heavy, and thresh.
test_general_fast_transform()
int test_general_fast_transform ()
References madness::nonlinear_vector_solver(), and run_heavy.
Referenced by main().
test_golden_values()
int test_golden_values (World & world)
References std::abs(), madness::test_output::checkpoint(), e(), madness::test_output::end(), madness::g, golden_pts, and madness::nonlinear_vector_solver().
Referenced by main().
test_output_param_overload()
int test_output_param_overload (World & world)
References madness::test_output::checkpoint(), d, e(), madness::test_output::end(), madness::f, madness::WorldGopInterface::fence(), madness::World::gop, L, NDIM, madness::nonlinear_vector_solver(), ok(), p(), madness::Function< T, NDIM >::reconstruct(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), and madness::FunctionDefaults< NDIM >::set_thresh().
Referenced by main().
test_scaling_factor()
int test_scaling_factor ()
References std::abs(), madness::arg(), madness::test_output::checkpoint(), madness::test_output::end(), madness::MAXLEVEL, and madness::nonlinear_vector_solver().
Referenced by main().
Variable Documentation
golden_pts
const GoldenPoint golden_pts[] static
Initial value:
= {
    {1, 7, 1e-5, { 0.3,  0.0,  0.0}},
    {1, 7, 1e-5, { 0.0,  0.0,  0.0}},
    {1, 7, 1e-5, {-0.5,  0.0,  0.0}},
    {2, 7, 1e-5, { 0.3,  0.3,  0.0}},
    {2, 7, 1e-5, { 0.1, -0.2,  0.0}},
    {3, 7, 1e-5, { 0.3, -0.3,  0.3}},
    {3, 7, 1e-5, { 0.0,  0.0,  0.0}},
}
Referenced by test_golden_values().
print_golden
const bool print_golden static
Initial value:
=
    (std::getenv("MADNESS_TEST_EVAL_PRINT_GOLDEN") != nullptr)
Referenced by golden_check_ndim().
run_bench
const bool run_bench static
Initial value:
=
    (std::getenv("MADNESS_BENCH_EVAL") != nullptr)
Referenced by main().
run_heavy
const bool run_heavy static
Initial value:
=
    (std::getenv("MADNESS_TEST_EVAL_EXHAUSTIVE") != nullptr)
Referenced by main(), test_correctness_ndim(), and test_general_fast_transform().