MADNESS: testbc.cc File Reference
testbc.cc File Reference
#include <madness/mra/mra.h>
#include <madness/mra/operator.h>
#include <madness/tensor/solvers.h>
#include <madness/constants.h>
Classes
class DSphere
Functor representing the log-derivative of along an axis.
class Sphere
Typedefs
typedef Vector< double, 3 > coordT
typedef FunctionFactory< double, 3 > factoryT
typedef Function< double, 3 > functionT
typedef std::shared_ptr< FunctionFunctorInterface< double, 3 > > functorT
typedef SeparatedConvolution< double, 3 > operatorT
typedef std::pair< vecfuncT, vecfuncT > pairvecfuncT
typedef std::shared_ptr< WorldDCPmapInterface< Key< 3 > > > pmapT
typedef std::shared_ptr< operatorT> poperatorT
typedef std::vector< pairvecfuncT > subspaceT
typedef Tensor< double > tensorT
typedef std::vector< functionT > vecfuncT
Functions
int main (int argc, char **argv)
Typedef Documentation
coordT
typedef Vector<double,3> coordT
factoryT
typedef FunctionFactory<double,3> factoryT
functionT
typedef Function<double,3> functionT
functorT
typedef std::shared_ptr< FunctionFunctorInterface<double,3> > functorT
operatorT
typedef SeparatedConvolution<double,3> operatorT
pairvecfuncT
typedef std::pair<vecfuncT,vecfuncT> pairvecfuncT
pmapT
typedef std::shared_ptr< WorldDCPmapInterface< Key<3> > > pmapT
poperatorT
typedef std::shared_ptr<operatorT> poperatorT
subspaceT
typedef std::vector<pairvecfuncT> subspaceT
tensorT
typedef Tensor<double> tensorT
vecfuncT
typedef std::vector<functionT> vecfuncT
Function Documentation
main()
int main (int argc, char ** argv)
References bufsize, c, madness::Function< T, NDIM >::clear(), SafeMPI::COMM_WORLD, madness::CoulombOperator(), e(), madness::error(), madness::f, madness::WorldGopInterface::fence(), madness::finalize(), madness::Tensor< T >::gaxpy(), madness::World::gop, madness::initialize(), k, madness::KAIN(), L, lo, m, mu, madness::nonlinear_vector_solver(), madness::Function< T, NDIM >::norm2(), madness::norm2(), op(), madness::constants::pi, madness::plot_line(), madness::print(), Q(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), sigma, madness::startup(), thresh, madness::Function< T, NDIM >::truncate(), and u().