MADNESS: testproj.cc File Reference
testproj.cc File Reference
test box size dependence of projection etc.
#include <madness/mra/mra.h>
#include <madness/constants.h>
#include <vector>
Classes
class Gaussian< T, NDIM >
Functions
int main (int argc, char **argv)
template<typename T , std::size_t NDIM>
int test_proj (World &world)
Variables
bool smalltest = true
Detailed Description
test box size dependence of projection etc.
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, e(), madness::error(), madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), madness::nonlinear_vector_solver(), madness::print(), smalltest, and madness::startup().
test_proj()
template<typename T , std::size_t NDIM> int test_proj (World & world)
References e(), madness::f, L, NDIM, madness::nonlinear_vector_solver(), madness::constants::pi, pow(), madness::print(), madness::World::rank(), madness::FunctionDefaults< NDIM >::set_autorefine(), madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::FunctionDefaults< NDIM >::set_truncate_on_project(), smalltest, and madness::Function< T, NDIM >::truncate().
Variable Documentation
smalltest
bool smalltest = true
Referenced by main(), and test_proj().