MADNESS: writecoeff3.cc File Reference
writecoeff3.cc File Reference
#include <FunctionIO.h>
#include <iostream>
#include <madness/mra/mra.h>
#include <memory>
Typedefs
typedef Vector< double, D > coordT
typedef double dataT
typedef FunctionFactory< dataT, D > factoryT
using fio = FunctionIO< double, D >
typedef Function< dataT, D > functionT
typedef std::shared_ptr< FunctionFunctorInterface< dataT, D > > functorT
typedef Key< D > keyT
typedef SeparatedConvolution< dataT, D > operatorT
Functions
static dataT f (const coordT &r)
int main (int argc, char **argv)
void test (World &world)
Variables
static const size_t D = 2
static const long k = 5
static const double L = 4.0
static const double thresh = 1e-3
Typedef Documentation
coordT
typedef Vector<double, D> coordT
dataT
typedef double dataT
factoryT
typedef FunctionFactory<dataT, D> factoryT
fio
using fio = FunctionIO<double, D>
functionT
typedef Function<dataT, D> functionT
functorT
typedef std::shared_ptr<FunctionFunctorInterface<dataT, D> > functorT
keyT
typedef Key<D> keyT
operatorT
typedef SeparatedConvolution<dataT, D> operatorT
Function Documentation
f()
static dataT f (const coordT & r) static
References madness::Vector< T, N >::normf(), and R.
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), test(), and thresh.
test()
void test (World & world)
References FunctionIO< T, NDIM >::count_leaf_nodes(), FunctionIOData< T, NDIM >::create_function(), madness::f, madness::nonlinear_vector_solver(), norm(), madness::norm2(), madness::print(), madness::World::rank(), madness::to_json(), and madness::Function< T, NDIM >::truncate().
Variable Documentation
D
const size_t D = 2 static
k
const long k = 5 static
Referenced by main().
L
const double L = 4.0 static
Referenced by main().
thresh
const double thresh = 1e-3 static
Referenced by main().