MADNESS: writecoeff2.cc File Reference
writecoeff2.cc File Reference
#include <complex>
#include <iomanip>
#include <iostream>
#include <madness/mra/mra.h>
#include <memory>
Typedefs
typedef Vector< double, D > coordT
typedef double dataT
typedef FunctionFactory< dataT, D > factoryT
typedef Function< dataT, D > functionT
typedef std::shared_ptr< FunctionFunctorInterface< dataT, D > > functorT
typedef Key< D > keyT
typedef SeparatedConvolution< dataT, D > operatorT
Functions
template<typename T , std::size_t NDIM>
size_t count_leaf_nodes (const Function< T, NDIM > &f)
static dataT f (const coordT &r)
int main (int argc, char **argv)
template<typename T , std::size_t NDIM>
Function< T, NDIM > read_function (World &world, std::istream &in)
template<typename T , std::size_t NDIM>
void read_function_coeffs (Function< T, NDIM > &f, std::istream &in)
void test (World &world)
template<typename T , std::size_t NDIM>
void write_function (const Function< T, NDIM > &f, std::ostream &out)
template<typename T , std::size_t NDIM>
void write_function_coeffs (const Function< T, NDIM > &f, std::ostream &out, const Key< NDIM > &key)
Variables
static const size_t D = 2
static const long k = 5
static const double L = 4.0
static const double thresh = 1e-3
Typedef Documentation
coordT
typedef Vector<double, D> coordT
dataT
typedef double dataT
factoryT
typedef FunctionFactory<dataT, D> factoryT
functionT
typedef Function<dataT, D> functionT
functorT
typedef std::shared_ptr<FunctionFunctorInterface<dataT, D> > functorT
keyT
typedef Key<D> keyT
operatorT
typedef SeparatedConvolution<dataT, D> operatorT
Function Documentation
count_leaf_nodes()
template<typename T , std::size_t NDIM> size_t count_leaf_nodes (const Function< T, NDIM > & f)
References madness::f, and madness::nonlinear_vector_solver().
Referenced by write_function().
f()
static dataT f (const coordT & r) static
References madness::Vector< T, N >::normf(), and R.
main()
int main (int argc, char ** argv)
References madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), k, L, madness::FunctionDefaults< NDIM >::set_cubic_cell(), madness::FunctionDefaults< NDIM >::set_initial_level(), madness::FunctionDefaults< NDIM >::set_k(), madness::FunctionDefaults< NDIM >::set_refine(), madness::FunctionDefaults< NDIM >::set_thresh(), madness::FunctionDefaults< NDIM >::set_truncate_mode(), madness::startup(), test(), and thresh.
read_function()
template<typename T , std::size_t NDIM> Function< T, NDIM > read_function (World & world, std::istream & in)
References d, madness::f, madness::WorldGopInterface::fence(), madness::World::gop, k, MADNESS_CHECK, NDIM, madness::nonlinear_vector_solver(), read_function_coeffs(), and madness::FunctionDefaults< NDIM >::set_cell().
read_function_coeffs()
template<typename T , std::size_t NDIM> void read_function_coeffs (Function< T, NDIM > & f, std::istream & in)
References madness::f, NDIM, madness::Tensor< T >::ptr(), and madness::BaseTensor::size().
Referenced by read_function().
test()
void test (World & world)
References madness::f, madness::nonlinear_vector_solver(), norm(), madness::Function< T, NDIM >::norm2(), madness::norm2(), madness::World::rank(), madness::Function< T, NDIM >::truncate(), and write_function().
write_function()
template<typename T , std::size_t NDIM> void write_function (const Function< T, NDIM > & f, std::ostream & out)
References count_leaf_nodes(), d, madness::f, madness::FunctionDefaults< NDIM >::get_cell(), NDIM, madness::nonlinear_vector_solver(), and write_function_coeffs().
Referenced by test().
write_function_coeffs()
template<typename T , std::size_t NDIM> void write_function_coeffs (const Function< T, NDIM > & f, std::ostream & out, const Key< NDIM > & key)
References madness::f, madness::Key< NDIM >::level(), NDIM, madness::nonlinear_vector_solver(), and madness::Key< NDIM >::translation().
Referenced by write_function().
Variable Documentation
D
const size_t D = 2 static
k
const long k = 5 static
Referenced by main(), and read_function().
L
const double L = 4.0 static
Referenced by main().
thresh
const double thresh = 1e-3 static
Referenced by main().